flyteorg/flyteconsole

src/components/Launch/LaunchWorkflowForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchWorkflowForm/SearchableSelector.tsx
src/components/Launch/LaunchWorkflowForm/__stories__/LaunchWorkflowForm.stories.tsx
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/components/Workflow/WorkflowDetails/WorkflowDetails.tsx
src/components/Workflow/WorkflowDetails/WorkflowDetailsHeader.tsx
src/models/Execution/api.ts
src/models/Execution/constants.ts

* Added a button to the WorkflowDetailsHeader to initiate launch
* Added some state to WorkflowDetails to handle showing a MUI Dialog with our form inside it
* Changed some of the launch form components to use MUI Dialog* components instead.
* Updated props for the form so that a partial workflow id can be passed, as well as a close handler
* Updated styling of the form to make sure we have enough room to show the versions list.
* Implemented the API call for creating an execution
* Implemented logic in the form's submission handler
* Added sort queries for search results and the pre-populated workflow version list
* Moved my 'latest' tagging logic to the pre-populated list, where it belongs. 😅 
* Added an effect to select the latest version of the workflow by default so that the form …

Integrate the Launch form

---

src/components/Launch/LaunchWorkflowForm/LaunchWorkflowForm.tsx

On a laptop screen, the minimum height for the contents of the launch form cause some ugly scrolling behavior. Given the space used by the other elements, I chose a smaller minHeight to keep the dialog+padding inside of 900px.

Set a more reasonable minHeight on launch form contents

---

package.json
src/components/Executions/ExecutionInputsOutputsModal.tsx
src/models/Execution/api.ts
yarn.lock

lyft/flyteidl#13 deprecates the usage of `computed_inputs` to store the inputs of an execution directly on the record. In the future, the inputs will have to be fetched just like outputs. This is a backwards-compatible implementation that handles both cases.
* Updated the components which display WorkflowExecution inputs/outputs to check for the existence of inputs on the execution closure. If they aren't found, we will attempt to fetch them using the execution data endpoint.
* Updated the model layer for execution data to ensure that inputs/outputs alway have at least an empty object. The interface definition guarantees that those properties will exist, and the components are set up to handle the empty object case (but not the undefined property case)
TODO:

Updated handling for execution inputs

---

src/components/SelectProject/ProjectList.tsx
src/components/SelectProject/SelectProject.tsx
src/components/SelectProject/constants.ts
src/components/common/ButtonLink.tsx

Project records now have optional description fields. This adds support for displaying the description in the cards shown in the project list. Projects with no description will show "(No description provided.)" as a placeholder.
* Added `ButtonLink` class to support using MUI link-style buttons with ReactRouter links under the hood
* Updated layout of cards in the projects list to look better with descriptions
* Updated the domain links to be Button-style links. This is more consistent with how MUI cards typically do actions

Add support for project descriptions

---

src/models/Project/api.ts
src/models/Project/test/api.test.ts
src/models/__mocks__/projectData.ts

The api function for projects was relying on lodash `sortBy` to pluck the `name` property and sort by those values. This doesn't work quite correctly with mixed-case values ('BProject' would sort before 'aproject' because the ascii code point for 'B' comes before 'a'). To correct this, the iteratee was replaced with a function that returns the names values as lowercase.

Fix project sorting to be case-insensitive

---

src/components/Navigation/ProjectNavigation.tsx
src/components/Project/ProjectDetails.tsx
src/components/Project/ProjectTasks.tsx
src/components/Project/ProjectWorkflows.tsx
src/components/Task/SearchableTaskNameList.tsx
src/components/Task/__stories__/SearchableTaskNameList.stories.tsx
src/components/Workflow/SearchableNamedEntityList.tsx
src/components/Workflow/SearchableWorkflowNameList.tsx
src/components/Workflow/__stories__/SearchableWorkflowNameList.stories.tsx
src/components/common/SearchableNamedEntityList.tsx
src/components/hooks/useNamedEntity.ts
src/models/Task/constants.ts
src/models/__mocks__/sampleTaskNames.ts
src/routes/routes.ts

This creates a view similar to the workflows list view, except for tasks.
For the moment, we just want to list the available tasks with their associated metadata (description). And a follow-up PR will also add the interface description for tasks.
* Added routes, side navigation for tasks list
* Updated `ProjectDetails` to support rendering different content based on the route (either workflows or tasks)
* Made most of `SearchableWorkflowNameList` generic so that it can be shared with the tasks list. The only difference between them is how the rows are rendered.
* Added hook for fetching task names/descriptions
* Added mock data for task ids/names

Tasks view

---

src/components/Project/ProjectTasks.tsx
src/components/common/SearchableNamedEntityList.tsx

Updated a flex property and also fixed a bad usage of a sort key constant (they end up being the same value, so it wasn't causing a bug)
Before:
After:

Fixing wrapping of values in task/workflow lists

---

src/common/utils.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/components/Literals/LiteralMapViewer.tsx
src/components/Literals/Scalar/ProtobufStructValue.tsx
src/components/Literals/Scalar/test/ProtobufStructValue.test.tsx
src/components/Literals/test/LiteralMapViewer.test.tsx
src/components/Task/SimpleTaskInterface.tsx
src/components/Task/test/SimpleTaskInterface.test.tsx

lyft/flyte#98
`Object.entries` and `Object.keys` don't guarantee an ordering. This is normally not a problem, except we directly render the result of calling these functions on an input/output object to the screen.
Since the API response also does not guarantee ordering, this can mean a re-ordering in the rendered content when we are polling for execution status and/or changing launch plan versions.
Consistency of display is preferred to optimal ordering of values, so for now we will sort the values lexicographically.
* Added helper functions for calling `Object.entries` and `Object.keys` and subsequently sorting the resulting arrays
* Updated the three places we use those built-ins to generate output to call the sorted versions instead.
* Wrote tests for the components in question to …

Sorting keys wherever we render inputs/outputs

---

Dockerfile
package.json

`snyk-protect` runs as part of the `yarn` installation process. It requires the presence of the `.snyk` file, which is not part of the minimal files we copy at that stage of the `Dockerfile`. This adds the `.snyk` file at the early stage and bumps the package version.

Fix Docker image build errors due to missing .snyk file

---

.snyk
jest.config.js
package.json
src/components/App/App.tsx
src/components/Errors/DataError.tsx
src/components/Errors/LoginExpiredHandler.tsx
src/components/Errors/test/DataError.test.tsx
src/components/Errors/test/LoginExpiredHandler.test.tsx
src/components/Navigation/DefaultAppBarContent.tsx
src/components/Navigation/UserInformation.tsx
src/components/Navigation/test/UserInformation.test.tsx
src/components/Navigation/useUserProfile.ts
src/components/data/apiContext.ts
src/components/hooks/useFetchableData.ts
src/components/hooks/useUserProfile.ts
src/errors/fetchErrors.ts
src/models/AdminEntity/AdminEntity.ts
src/models/AdminEntity/test/utils.spec.ts
src/models/AdminEntity/transformRequestError.ts
src/models/AdminEntity/utils.ts
src/models/Common/api.ts
src/models/Common/constants.ts
src/models/Common/types.ts
src/test/setupTests.ts
yarn.lock

* Added hook for retrieving user information.
* Added api layer for fetching user information. By design, it will _never_ fail, but instead return null in the case of a 401. This is because Admin returns a 401 in both the case of not being logged in and the case of the user's session expiring.
* Centralized error handling logic for `/api/v1` requests.
* Updated `APIContext` to include information about the login state
* Updated `useFetchableData` to toggle the `expired` login state whenever we receive a 401.
* Added a global dialog component that listens for expired login state and shows a dialog directing the user to re-authenticate.
* Added error handling for 401, we now return a special error for that case (similar to 404).
* Updated `DataError` to render nothing in the case of a 401, …

Integrate Authentication

---

src/common/constants.ts
src/components/Executions/ExecutionDetails/ExecutionNodeDetails/TaskExecutionNodeDetails.tsx
src/components/Executions/Tables/NoExecutionsContent.tsx
src/components/Executions/Tables/WorkflowExecutionsTable.tsx
src/components/Executions/Tables/test/NodeExecutionChildren.test.tsx
src/components/Executions/TaskExecutionsList/TaskExecutionsList.tsx
src/components/Executions/TaskExecutionsList/test/TaskExecutionsList.test.tsx
src/components/Executions/useTaskExecutions.ts
src/components/Tables/DataTable.tsx

See lyft/flyte#86
We have two places where we show a list of task executions. One of them was already doing sorting of the list by creation time, but was doing it in the component itself. Task executions support sorting when fetching from the API, so this should at least be done when requesting the data.
Since we always list them in order of creation, I put the sorting into the hook that is shared by both components.
* Removed explicit sort in `TaskExecutionsList`
* Updated `useTaskExecutions` to always request a sort by created_at, ascending
* Added tests for `TaskExecutionsList` and `NodeExecutionChildren` to ensure empty states and that the request includes the expected sort values
* Cleanup: Moved a string that appears as a literal in a few places into a constant

Ensure TaskExecutions are always listed in the correct order.

---

src/common/utils.ts
src/components/Launch/LaunchWorkflowForm/__mocks__/mockInputs.ts
src/components/Launch/LaunchWorkflowForm/__mocks__/utils.ts
src/components/Launch/LaunchWorkflowForm/__stories__/LaunchWorkflowForm.stories.tsx
src/components/Launch/LaunchWorkflowForm/inputHelpers/boolean.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/collection.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/constants.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/datetime.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/duration.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/float.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/inputHelpers.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/integer.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/none.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/string.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/testCases.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/types.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/utils.ts
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/useFormInputsState.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/models/Common/types.ts

Fixes lyft/flyte#18 
This change adds support for default values when populating the Launch form. The default values are read from the selected launch plan and set as the initial value for the state hooks used to handle input interaction.
* Added `fromLiteral` function to all `InputHelper` implementations. This function is intended to parse a `Core.ILiteral` (the type used for default values) into an `InputValue` which can be used to populate a control in the Launch form
* Added `defaultValue` static property to `InputHelper`. For most types, this will be unset/undefined, because the default for an untouched control should be completely empty. For booleans, the default value will be set to `false`. This is because a toggle can't have an empty state and it causes issues when we send a …

Adds support for default values

---

src/components/Launch/LaunchWorkflowForm/getInputs.ts
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/test/constants.ts
src/components/Launch/LaunchWorkflowForm/test/getInputs.test.ts
src/components/Launch/LaunchWorkflowForm/test/utils.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/models/Common/types.ts

* Split the `getInputs` function into a separate file to make it easier to test
* Added a loose null check to handle both null/undefined for the value of the `default` property. This prevents us from attempting to read properties on a null object.
* Added a test for the regression

Correctly handling null default value properties

---

Dockerfile

I removed the Snyk integration a while ago and missed the line from the Dockerfile which attempts to copy the Snyk config file. This change removes the offending command.

Removing command in Dockerfile to copy a non-existent file

---

src/components/Launch/LaunchWorkflowForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchWorkflowForm/__stories__/LaunchWorkflowForm.stories.tsx
src/components/Launch/LaunchWorkflowForm/inputValueCache.ts
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/useExecutionLaunchConfiguration.ts
src/components/Launch/LaunchWorkflowForm/useFormInputsState.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/components/Launch/LaunchWorkflowForm/utils.ts
src/components/Literals/RemoteLiteralMapViewer.tsx
src/components/Literals/constants.ts
src/components/hooks/types.ts
src/components/hooks/useRemoteLiteralMap.ts
src/components/hooks/useWorkflowExecution.ts
src/models/Common/api.ts

lyft/flyte#84
This is the bulk of the work needed to support a "Relaunch with edits" experience. It adds the ability for the launch form state to be initialized from specific parameters.
**Workflow Version**
The launch form can be pre-initialized to point to a specific workflow version. The provided version will be included in the fetching of workflow versions to show in the selector, and we will attempt to select that version after loading the options. Fallback behavior is to select the first item in the list (the latest version)
**Launch Plan**
Providing a launch plan id will cause that launch plan to be preferred. Similar to workflow versions, it will be included in the fetching of options. If we can't select the desired launch plan, we fall back to the first item in the list. …

Adds support for initializing the Launch form using a workflow/launch plan/ inputs

---

src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts

Some testing discovered the following issues:
* Selecting the already-selected version in the Workflow Version dropdown causes the LaunchPlan to be de-selected.
* This was caused by allowing the workflow selection code to run even when the value is the same. Since we clear the selected launch plan in response to that, and the effects which would auto-select the launch plan do not run (because no inputs have _actually_ changed), it results in a de-selection of the launch plan. The fix is to bail out early if we're attempting to select the currently selected items. 
* When re-launching an execution, there are two copies of the same LaunchPlan name in the selector.
* This was caused by a bad destructuring of the input. I had meant to extract the `id.name` property for comparison when …

Fixing small issues with new Launch functionality

---

package.json
webpack.config.ts
yarn.lock

With the recent dependency upgrades, running the docker build is hanging on the forked Typescript processes launched by Happypack.
A little investigation revealed that Happypack has been deprecated by its author, and that in Webpack 4+ environments it doesn't add much benefit. So I've removed it from our config and ✨ the docker build finishes again. ✨ I may come back later and investigate using `thread-loader` to get an extra performance benefit.
I also re-ordered the resolve config to prefer typescript extensions when searching.

Fixing hanging docker build

---

src/components/Launch/LaunchWorkflowForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
webpack.config.ts

There is a fetch function used to search for workflow versions. It was relying on the incoming workflow id to be only partially specified. In the case of a relaunch, the workflow id will include a version, but that version should not be included in the `scope` value we pass to the list endpoint function.
Also during this fix, I was running into OOM crashes with `ts-loader` because it was doing type-checking in addition to transpiling. In our webpack setup, we are using the forked checker plugin for type checking, so `ts-loader` should be put into `transpileOnly` mode.
And I also cleaned up the timer usage in the launch form tests, because I was getting arbitrary infinite timer loops due to the 
Before:
After:

Fixing a bug with searching workflow versions when relaunching an execution

---

package.json
src/components/flytegraph/layoutUtils.ts
src/tsd/d3-dag.d.ts
yarn.lock

lyft/flyte#182
The update to @date-io/moment made it incompatible with `moment.utc` due to a direct reference made to `.weekdaysShort`, which won't exist on the object we are passing. ([See this change](https://github.com/dmtrKovalenko/date-io/commit/57ede054e4fa9130d0cf45872bba42ee2d319d08#diff-d94d646e6354db094f3dd121e325edd1))
For now, I've fixed the version to the last known working version. We can do an explicit update to the latest version later on, as it will also involve updating material-pickers.
lyft/flyte#179
`d3-dag` made some backwards incompatible renames between 0.1 and 0.2. I updated our local type definitions and the reference to `dratify`.

Fixes reference errors after dependency upgrades

---

src/components/Launch/LaunchWorkflowForm/inputHelpers/collection.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/utils.ts

lyft/flyte#181
When converting `Literal` values to `InputValue`s for use in the form, the `Collection` type is output as a JSON representation of an array. The existing implementation was blindly wrapping `[]` around values and comma-separating them. For Dates and strings, the resulting array string is not valid JSON and will trigger validation errors.
It turned out to be easier to allow `JSON.stringify` to do this work for us, with the exception of integers. Since we use a special type for integers, `stringify` would result in a quoted string value instead of a bare integer value.

Fixes initial population of values for string Collections in the launch form.

---

src/components/Launch/LaunchWorkflowForm/SearchableSelector.tsx
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx

lyft/flyte#140
Previously, we would clear the value of this input every time the user focused, so that they could begin typing right away. The goal was convenience. But it makes it difficult to copy the value from the input.
A solution that covers both needs is to simply highlight the contents on focus, so they are copyable and so that typing will have the effect of clearing the existing value.

Select contents of workflow version selector on focus

---

src/components/Launch/LaunchWorkflowForm/UnsupportedInput.tsx
src/components/Launch/LaunchWorkflowForm/getInputs.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/inputHelpers.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/useExecutionLaunchConfiguration.ts
src/components/Launch/LaunchWorkflowForm/useFormInputsState.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts

lyft/flyte#186
For some input types, we don't yet have editing support in Flyte Console. This caused a regression when changing our relaunch flow to use the form (see the above issue). 
However, it's possible for us to preserve the `Literal` that we extracted from the source execution and pass it along unmodified when we relaunch the execution. This change enables that behavior by changing the types passed down to our input state to be a `Core.ILiteral` until it is actually necessary to convert it to an `InputValue`. When the form is submitted, if there is no user-provided value, but there *is* an initial value, we will send that instead.
* Updated `ParsedInput` and `InputProps` to add the `initialValue` field. Removed the `defaultValue` field.
* Moved the logic for converting from …

Preserves unsupported input types when relaunching

---

.dockerignore
env.js
index.js
plugins.js
src/config/types.ts

This is the first change set for implementing a global notification banner. _Note_: This is being opened against a feature branch, as this is not the completely implementation of the change.
* Added ability for the console server to load custom middleware. This makes it possible to implement additional endpoints in private code that will be added to the console server at runtime.
* Added environment variable for `STATUS_URL`. This will be used in an upcoming change to ping for system status and conditionally show the notification banner.
* Updated Dockerfile excludes.
https://github.com/lyft/flyte/issues/223

Status endpoints

---

src/components/App/App.tsx
src/components/Notifications/SystemStatusBanner.tsx
src/components/Notifications/__stories__/SystemStatusBanner.stories.tsx
src/components/Notifications/useSystemStatus.ts
src/components/Theme/constants.ts
src/models/Common/api.ts
src/models/Common/constants.ts
src/models/Common/types.ts

lyft/flyte#223
This implements the status banner that will show whatever status/message is retrieved from the `STATUS_URL` endpoint. There are two possible icons (info and warning). The banner will only show if the `message` field of the status is provided. The banner is dismissable per-session and will return on refresh for as long as the status message exists.
Still to do in future PRs:
* Tests
* Automatically parse and render links

Status banner

---

package.json
src/components/Executions/constants.ts
src/models/Execution/__mocks__/mockTaskExecutionsData.ts
src/models/Execution/__mocks__/mockWorkflowExecutionsData.ts
src/models/__mocks__/sampleTaskNames.ts
src/models/__mocks__/sampleWorkflowNames.ts
yarn.lock

* Upgraded `flyteidl`
* Added entries to task execution phase constants to handle the two new phase values ("waiting for resources" and "initializing")
* Fixed a few other errors in mock data due to some proto messages getting additional required fields.

Handle new TaskExecutionPhase values

---

src/components/Notifications/SystemStatusBanner.tsx
src/components/Notifications/test/SystemStatusBanner.test.tsx
src/components/common/Empty.tsx

`SystemStatusBanner` should not show anything unless it has successfully loaded and a `message` property exists. However, since it uses `WaitForData`, it will show a loading spinner and any resulting errors unless those are explicitly disabled.
This PR uses a simple `Empty` component as the override for both loading and error states to ensure that `WaitForData` will only render the banner on a successful load, and nothing in the other cases.

Ensuring banner shows no content while loading or in an error state

---

.travis.yml
Makefile
README.rst
jest.config.js
package.json

The PR publishes test coverage report to codecov.io. This allows tracking every checkin and the code coverage over time
Same as TL;DR
https://github.com/lyft/flyte/issues/260
NA

Code Coverage published to codecov.io

---

.travis.yml
Makefile
package.json
yarn.lock

This removes the usage of npm and a global package install during our code coverage make target. It also separates the coverage out into a separate testing command, since generating coverage slows down the local development flow and only needs to be run in the CI environment.

Removes global package install for codecov

---

src/components/Project/ProjectWorkflows.tsx
src/components/Project/test/ProjectWorkflows.test.tsx
src/test/modelUtils.ts
yarn.lock

NamedEntities can now have a `state` value indicating they are `archived`. The goal of this is to allow users to archive workflows so that they aren't cluttering up the UI. Supporting this in the UI is fairly trivial (update our list request to add a filter for only the active state).
I also added a test file for ProjectWorkflows and a test to assert that we are filtering to only active workflows and updated the yarn.lock file.

Hide archived workflows in Console

---

src/components/Cache/utils.ts
src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
src/components/Executions/ExecutionDetails/contexts.ts
src/components/Executions/Tables/NodeExecutionRow.tsx
src/components/Executions/Tables/test/NodeExecutionsTable.test.tsx
src/components/Executions/types.ts
src/components/Executions/useChildNodeExecutions.ts
src/components/Executions/useTaskExecutions.ts
src/components/Executions/useWorkflowExecutionState.ts
src/components/hooks/useNodeExecutions.ts

One of the end goals of our dynamic task experience changes is that instead of the hierarchy in the table being `NodeExecution -> TaskExecution/WorkflowExecution -> NodeExecution`, we remove the intermediate entity and make it `NodeExecution -> NodeExecution`.
This creates some issues:
* To determine if a NodeExecution can be expanded, we need to know if it has any children. There is no property on a NodeExecution that tells us that it has children. To determine that information, we need different behavior based on the node type.
* For Task nodes (dynamic tasks), we will need to fetch the TaskExecutions created by the given NodeExecution. For each TaskExecution, we need to fetch its child NodeExecutions.
* For Workflow nodes (specifically those that launch a separate WorkflowExecution), …

refactor: fetch child node executions for NodeExecution rows

---

src/components/Executions/Tables/NodeExecutionChildren.tsx
src/components/Executions/Tables/NodeExecutionRow.tsx
src/components/Executions/Tables/NodeExecutionsTable.tsx
src/components/Executions/Tables/WorkflowExecutionsTable.tsx
src/components/Executions/Tables/__stories__/NodeExecutionsTable.stories.tsx
src/components/Executions/Tables/styles.ts
src/components/Executions/Tables/utils.ts
src/components/Executions/utils.ts
src/components/hooks/test/utils.test.ts
src/components/hooks/useNodeExecution.ts
src/components/hooks/utils.ts
src/models/Common/types.ts
src/models/Execution/__mocks__/mockTaskExecutionsData.ts
src/models/Workflow/types.ts

This is a general cleanup PR for leftover small tasks related to our Dynamic Tasks refactor. The bulk of the work is:
* Styling logic updates to `NodeExecutionsTable` and its children.
* Getting the stories for `NodeExecutionsTable` functional again.
Detailed breakdown:
* Refactored classes/containers for `NodeExecutionRow` and `NodeExecutionChildren` to better support dynamic left spacing based on nesting level.
* Added props for `level` and `index` to row components
* Added logic to adjust left padding/margin for rows to accomplish the spacing/border scheme shown in the screenshot below
* Fixed styling on child group labels to render them with padding and thicker top/bottom borders
* Fixed a few direct usages of api calls without apiContext which were causing real network requests in …

fix: cleanup for dynamic tasks refactoring

---

.editorconfig
.github/workflows/pull_request.yml
.github/workflows/release.yml
.prettierrc.yml
.releaserc.json
CHANGELOG.md
commitlint.config.js
package.json
src/components/Executions/test/utils.test.ts
src/components/Workflow/WorkflowVersionDetails/test/__snapshots__/WorkflowVersionDetailsContent.spec.tsx.snap
src/components/common/DropDownWindowButton.tsx
yarn.lock

* Pulled in the latest `boilerplate` to get some shared github actions.
* Began using the GH action to build/push images for pull requests
* Added a `semantic-release` config to allow automatic generation of release notes and releases when merging changes to master. See [semantic-release docs](https://github.com/semantic-release/semantic-release) for more info.
* Added commit linting to ensure that commits follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) standards. This helps us with the automatic release generation process.
* fixed a test that was flaky on CI due to the expectation that an event loop would take at least 1ms to complete.

feat: Adding automatic image building and release management

---

package.json
src/components/Executions/ExecutionDetails/ExecutionDetails.tsx
src/components/Executions/ExecutionDetails/ExecutionDetailsAppBarContent.tsx
src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
src/components/Executions/ExecutionDetails/constants.ts
src/components/Executions/ExecutionDetails/test/ExecutionMetadata.test.tsx
src/components/Theme/constants.ts
src/models/__mocks__/executionsData.ts
yarn.lock

The primary goal was to expose a piece of metadata that is useful in debugging. But since the portion of the page where we show execution details is already pretty crowded, I decided to implement a restyling that would be part of some upcoming design changes for the execution details page. This gave me more room to add the extra piece of information
* Moved most details out of header into a separate section below the header, which is collapsible
* Updated execution name to render all as one string, making it easier to copy
* Updated styling of details
* Added 'Cluster' detail. Executions with no `spec.metadata.systemMetadata.executionClusterName` property will just show "(unknown)"
* Added errors for WorkflowExecutions, shown at the bottom of the metadata section
Before:
After: …

fix: Expose cluster information for Workflow Executions

---

src/common/constants.ts
src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
src/components/Executions/ExecutionDetails/test/ExecutionMetadata.test.tsx

This is a small fix to correct a poor experience. My previous implementation of the execution metadata section would completely hide the start time / duration if they didn't have a value.  In order to be consistent, I've updated it to show dashes in the case of a missing value, so that the element is always present. I also updated the "Cluster" element to show dashes in the case of a missing value.

fix: show dashed lines for empty values instead of removing them

---

src/components/Executions/Tables/ExpandableExecutionError.tsx
src/components/Executions/Tables/WorkflowExecutionsTable.tsx
src/components/common/ExpandableMonospaceText.tsx

lyft/flyte#64
Since we use virtualization, the components used to render the rows in this table are unmounted every time they leave the viewport. This is great for performance, but it resets state when the component comes back into view. To account for this, we're now storing the expansion state for errors at the table level, and piping them through as an initial state when mounting the components. This will maintain the expansion state when the component leaves and reenters the viewport.
Note: This change _should_ have a corresponding unit test. However, since jsdom does not support layout, we can't test scrolling the component out of the viewport and back in. So it's not possible at the moment to write a unit test for it :-(
Before: 
After:

fix: prevents collapsing of execution errors when scrolled out of view

---

src/common/formatters.ts
src/common/test/formatters.spec.ts

lyft/flyte#97
For values that are less than 1 second, we can/should show `(value)ms` instead of just showing `<1s`. The exact millisecond value is preferable when rendering inputs/outputs.

fix: show full millisecond values for subsecond durations

---

src/common/utils.ts
src/components/Launch/LaunchWorkflowForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchWorkflowForm/UnsupportedRequiredInputsError.tsx
src/components/Launch/LaunchWorkflowForm/__stories__/LaunchWorkflowForm.stories.tsx
src/components/Launch/LaunchWorkflowForm/constants.ts
src/components/Launch/LaunchWorkflowForm/getInputs.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/testCases.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/utils.test.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/utils.ts
src/components/Launch/LaunchWorkflowForm/styles.ts
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/test/constants.ts
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/components/Launch/LaunchWorkflowForm/utils.ts

lyft/flyte#291
This change improves the experience when a user is attempting to launch a Workflow for which it is impossible to specify a required value.
This can happen if the Workflow defines a required input with a type that the Console doesn't support yet (such as Schema, Binary, etc). If the Launch Plan specifies a default value, or we are re-launching an execution from which we can copy the value, it is still possible to proceed. Otherwise, we won't be able to successfully launch.
The previous experience was a little confusing, because we would only show a generic error at the bottom of the form after attempting to submit. The new experience is to show the user an error message indicating which inputs are unsupported, and directing them to either select a Launch Plan which provides …

fix: show info message for un-launchable workflows

---

src/components/Launch/LaunchWorkflowForm/BlobInput.tsx
src/components/Launch/LaunchWorkflowForm/LaunchWorkflowFormInputs.tsx
src/components/Launch/LaunchWorkflowForm/__mocks__/mockInputs.ts
src/components/Launch/LaunchWorkflowForm/__mocks__/utils.ts
src/components/Launch/LaunchWorkflowForm/__stories__/LaunchWorkflowForm.stories.tsx
src/components/Launch/LaunchWorkflowForm/constants.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/blob.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/boolean.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/collection.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/datetime.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/duration.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/float.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/getHelperForInput.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/inputHelpers.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/integer.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/string.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/test/testCases.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/types.ts
src/components/Launch/LaunchWorkflowForm/inputHelpers/utils.ts
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/utils.ts
src/components/Theme/constants.ts
src/components/Theme/muiTheme.ts
src/models/Common/types.ts

lyft/flyte#378
This adds basic input support for blobs by rendering a micro form containing `uri`, `format` and `dimensionality` sub-inputs. The only required input from a user is the `uri` field. Dimensionality is technically required, but is implemented with a select control that defaults to a value. So it's not possible for a user to specific an empty dimensionality in the simple case.
Collections of Blobs are also supported, following the same rules as other input types (it is specified with a JSON array string). In this case, each value must include a `uri` and `dimensionality`.
`format` is always optional and must be a string.

feat: Enables support for Blobs on the Launch form

---

src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
src/components/Executions/ExecutionDetails/constants.ts
src/components/Executions/ExecutionDetails/test/ExecutionNodeViews.test.tsx
src/components/Executions/__mocks__/createMockExecutionEntities.ts
src/components/Executions/filters/constants.ts
src/components/Executions/filters/useExecutionFiltersState.ts
src/components/hooks/useTabState.ts

lyft/flyte#425
We share the loaded NodeExecutions between the two tabs on the ExecutionDetails page.
This is a useful performance optimization when both are viewing an unfiltered list of NodeExecutions. But it results in missing node information when a filter is applied in the Nodes tab and then the Graph tab is opened.
To address this, I updated the logic in `ExecutionNodeViews` to only pass the filter list if the current tab is the Nodes tab. This has the effect of resetting the fetchable for NodeExecutions when the tab is changed if a filter is applied. But if no filter is applied, the passed list will be empty in all cases, resulting in reuse of the previously-fetched data.
The majority of this PR is actually cleanup work done to facilitate writing a unit test to cover the new …

fix: only filter NodeExecutions when viewing the Nodes tab

---

env.js
src/common/utils.ts
src/config/types.ts
src/models/AdminEntity/AdminEntity.ts

FlyteConsole enables authentication by default. This has a weird side-effect in Sandbox, where the console enables secure cookies, even if we actually do not have authN. in this situation, Chrome does not allow CORS with a wild card of `*`. This PR allows disabling authN and which should allow working with CORs
- [-] Unit tests added
Disable credentials in case when authn is not used / required. This will allow CORs wildcard. Particularly helpful in sandbox testing.
https://github.com/lyft/flyte/issues/416
_NA_

feat: Authentication can be optionally disabled

---

src/components/Errors/test/DataError.test.tsx
src/components/Executions/ExecutionDetails/ExecutionDetailsAppBarContent.tsx
src/components/Executions/ExecutionDetails/constants.ts
src/components/Executions/ExecutionDetails/test/ExecutionDetailsAppBarContent.test.tsx
src/components/common/MoreOptionsMenu.tsx
src/components/common/constants.ts
src/components/common/test/MoreOptionsMenu.test.tsx
src/test/utils.ts

lyft/flyte#468
This allows "relaunch" functionality for an execution which hasn't yet finished. This is helpful for some users who would like to launch multiple copies of an execution with slightly different input parameters.
Also fixed a warning from a test using a deprecated jest-dom method.

feat: Allow cloning of running executions

---

.github/workflows/pull_request.yml

lyft/flyte#495
We don't need images for every PR and it breaks checks on forks. So I'm removing the pushing from the PR checks and just doing a simple build to verify that the Dockerfile isn't broken.

ci: dont push docker images for PRs

---

src/components/Entities/EntityDetails.tsx
src/components/Entities/EntityDetailsHeader.tsx
src/components/Entities/EntityExecutions.tsx
src/components/Entities/generators.ts
src/components/Task/SearchableTaskNameList.tsx
src/routes/ApplicationRouter.tsx
src/routes/components.ts

This adds plumbing and interaction to allow users to navigate to the details page for a Task. It works pretty much the same as the behavior for Workflows.
* Wrapped items in SearchableTaskList in `Link`s, and added chevrons to indicate that they navigate to details upon click.
* Added necessary items in `routes` to allow navigating to TaskDetails view.
* Updated `EntityDetailsHeader` so that the back link changes depending on what type of entity we are rendering (so that clicking back from a Task takes you to the Tasks section instead of Workflows)
* (chore) Removed an unnecessary fragment in EntityDetailsHeader

feat: adding route and navigation to the task details page

---

src/components/Executions/ExecutionDetails/ExecutionNodeDetails/OutputNodeDetails.tsx
src/components/Executions/ExecutionDetails/NodeExecutionData.tsx
src/components/Executions/ExecutionDetails/NodeExecutionInputs.tsx
src/components/Executions/ExecutionDetails/NodeExecutionOutputs.tsx
src/components/Executions/ExecutionInputsOutputsModal.tsx
src/components/Literals/RemoteLiteralMapViewer.tsx
src/components/Literals/test/RemoteLiteralMapViewer.test.tsx
src/models/Execution/types.ts

Fixes Input/Output view when using GCS.
flyteadmin doesn't know how to return public URLs for GCS objects. It returns URL in format `gs://...` that doesn't work.  This fixes Input/Output view when using GCS for Storage by using new fullInputs/fullOutputs fields in getExecutionData proto. Change is backward-compatible, if full inputs/outputs aren't present, it's going to fallback on the existing mechanism.
I had to take https://github.com/lyft/flyteconsole/commit/6a3b80f175b357bc81fd5f7fea31c8e89d13cd0d and few other commits because I needed new fields in flyteidl.
https://github.com/lyft/flyte/issues/444
_NA_

Get full inputs/outputs from execution data

---

src/components/Literals/Scalar/PrimitiveValue.tsx
src/components/Literals/Scalar/test/PrimitiveValue.test.tsx

Render timestamp of protobuf in UTC.
When rendering a timestamp field of protobuf, local time instead of UTC is used. This is not consistent with other part of the UI. This PR switches to UTC instead of local timezone.
https://github.com/lyft/flyte/issues/80
_NA_

fix: Render timestamp of protobuf in UTC

---

package.json
src/components/Launch/LaunchWorkflowForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchWorkflowForm/launchMachine.ts
src/components/Launch/LaunchWorkflowForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchWorkflowForm/types.ts
src/components/Launch/LaunchWorkflowForm/useLaunchWorkflowFormState.ts
src/components/Launch/LaunchWorkflowForm/useWorkflowSourceSelectorState.ts
src/components/common/constants.ts
src/components/hooks/useFetchableData.ts
src/components/hooks/useQueryState.ts
yarn.lock

This migrates the state representations for `LaunchWorkflowForm` into a xstate state machine. Previously, a lot of logic and context variables were store in `useLaunchWorkflowFormState`. Now, all of the states in the flow are represented in `launchMachine`, which is consumed by the state hook.
The machine uses a handful of services to do the async work. These are provided by the state hook.
I also moved the state management for the workflow/launch plan selectors into a separate state hook. This is in preparation for making the launch form state generic enough to handle either a workflow or task as a source.
The net result of this should be no change in functionality.
*Note*: There are some TODOs left on this branch. This PR is against a feature branch, and I intend to address them in a …

Refactor Launch form to use a state machine

---

src/components/Launch/LaunchForm/LaunchForm.tsx
src/components/Launch/LaunchForm/LaunchFormInputs.tsx
src/components/Launch/LaunchForm/LaunchTaskForm.tsx
src/components/Launch/LaunchForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchForm/UnsupportedRequiredInputsError.tsx
src/components/Launch/LaunchForm/__mocks__/mockInputs.ts
src/components/Launch/LaunchForm/__stories__/LaunchForm.stories.tsx
src/components/Launch/LaunchForm/constants.ts
src/components/Launch/LaunchForm/getInputs.ts
src/components/Launch/LaunchForm/launchMachine.ts
src/components/Launch/LaunchForm/services.ts
src/components/Launch/LaunchForm/test/LaunchForm.test.tsx
src/components/Launch/LaunchForm/test/LaunchTaskForm.test.tsx
src/components/Launch/LaunchForm/test/LaunchWorkflowForm.test.tsx
src/components/Launch/LaunchForm/test/constants.ts
src/components/Launch/LaunchForm/test/getInputs.test.ts
src/components/Launch/LaunchForm/test/utils.ts
src/components/Launch/LaunchForm/types.ts
src/components/Launch/LaunchForm/useExecutionLaunchConfiguration.ts
src/components/Launch/LaunchForm/useLaunchTaskFormState.ts
src/components/Launch/LaunchForm/useLaunchWorkflowFormState.ts
src/components/Launch/LaunchForm/useTaskSourceSelectorState.ts
src/components/Launch/LaunchForm/useVersionSelectorOptions.ts
src/components/Launch/LaunchForm/useWorkflowSourceSelectorState.ts
src/components/Launch/LaunchForm/utils.ts
src/models/__mocks__/simpleTaskClosure.json
src/models/__mocks__/taskData.ts

* Added `LaunchTaskForm` and associated state hooks
* Refactored unit tests for LaunchForm and created additional set of tests for the 'task' case
* Updated some shared functionality to be usable with both workflows and tasks
* Updated `LaunchForm` to use new component if a taskId is specified.

feat: Add Task support to Launch form

---

src/components/Entities/generators.ts

lyft/flyte#542
The fix for the above bug in Admin will update the filter for single task executions to be based on `task.name` instead of `launch_plan.name`. So this PR updates the filter used in `EntityDetails` (in the task case) to use the new field.

fix: use correct filter for single task executions

---

src/components/hooks/test/usePagination.test.tsx
src/components/hooks/types.ts
src/components/hooks/usePagination.ts

lyft/flyte#546
`usePagination` stores the pagination token in separate state hook. After the `useFetchableData` refactor to use state machines, the fetchable will now reset before we have a change to update the token state, causing the value to persist across API calls. This update `usePagination` to store the token in the fetchable data, so that it is part of the context used by the state machine and will remain in sync with the data it applies to.
Also removed the unnecessary use of a separate state hook for the `moreItemsAvailable` field, since that can be directly computed from the presence of the `token`.
Since `usePagination` returns an object that mostly looks like a `FetchableData<T>`, but using a different context shape under the hood, it was necessary to update the type for …

fix: race condition with pagination token

---

package.json
src/components/Executions/Tables/NodeExecutionChildren.tsx
src/components/Executions/Tables/NodeExecutionRow.tsx
src/components/Executions/Tables/RowExpander.tsx
src/components/Executions/Tables/constants.ts
src/components/Executions/Tables/test/NodeExecutionsTable.test.tsx
src/components/Executions/TaskExecutionsList/utils.ts
src/components/Executions/types.ts
src/components/Executions/useChildNodeExecutions.ts
src/components/Executions/useExecutionDataCache.ts
src/components/Executions/utils.ts
src/models/AdminEntity/types.ts
src/models/Execution/constants.ts
src/models/Execution/types.ts
yarn.lock

lyft/flyte#438
This builds on the work from lyft/flyteadmin#111 to directly query NodeExecution children for NodeExecutions which use the new `isParent` flag. Most of the work was in the `useChildNodeExecutions` and `useExecutionDataCache` hooks to use the right logic for building a query for the node_executions endpoint.

feat: Fetch Node Executions directly if possible

---

package.json
src/common/formatters.ts
src/common/test/formatters.spec.ts
src/components/Entities/EntitySchedules.tsx
src/components/Launch/SchedulesTable.tsx
src/components/Launch/constants.ts
yarn.lock

Render CronSchedule with optional `offset` value.
https://github.com/lyft/flyte/issues/529
_NA_

feat: render CronSchedule

---

src/components/Executions/types.ts
src/components/Executions/useChildNodeExecutions.ts
src/components/Executions/utils.ts

lyft/flyte#438
In implementing the original changes to use the `isParentNode` flag, I had assumed that the flag would be completely absent. But due to the way protobuf is deserialized, when the metadata object is present, `isParentNode` will default to `false`. This will cause us to incorrectly skip checking for children on legacy node executions by querying the child TaskExecutions first.
So, the logic is now to query directly for child node executions if the flag is true, and fall back to the legacy check otherwise.

fix: don't skip legacy children check when isParentNode=false

---

src/components/Launch/LaunchForm/LaunchFormInputs.tsx
src/components/Launch/LaunchForm/SimpleInput.tsx
src/components/Launch/LaunchForm/__mocks__/utils.ts
src/components/Launch/LaunchForm/constants.ts
src/components/Launch/LaunchForm/inputHelpers/constants.ts
src/components/Launch/LaunchForm/inputHelpers/getHelperForInput.ts
src/components/Launch/LaunchForm/inputHelpers/schema.ts
src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchForm/inputHelpers/test/testCases.ts
src/components/Launch/LaunchForm/inputHelpers/test/utils.test.ts
src/components/Launch/LaunchForm/inputHelpers/utils.ts
src/components/Launch/LaunchForm/types.ts
src/components/Launch/LaunchForm/utils.ts

Adds Launch form support for the Schema input type. The Schema structure will be pulled from the Task or Workflow closure. The user only needs to provide a `uri` indicating the location of the schema to load.
Adding an input was fairly straightforward. Since the only input we need is a string value, I reused all of the Simple input code paths to render a single text field. Parsing a Literal to an input value just requires reading the `uri` field off of the incoming Literal value.
The complication is in converting the input string to the final Literal value. The `type` value of the resulting `Literal` needs to be the `schema` value from the type definition in the source Task/Workflow closure. But the code for doing the parsing only had access to our mapped `InputType` enum and the input's …

feat: Support Schema type in the Launch form

---

src/components/Launch/LaunchForm/launchMachine.ts
src/components/Launch/LaunchForm/test/LaunchTaskForm.test.tsx
src/components/Launch/LaunchForm/test/LaunchWorkflowForm.test.tsx

There was a missing state transition between the invalid inputs state and the submission/validation state, causing the state machine to do nothing when attempting to submit after fixing validation errors. The fix just required adding an allowed state transition and corresponding unit tests.
_N/A_
https://github.com/lyft/flyte/issues/565

fix: unable to submit after fixing validation errors

---

src/common/utils.ts
src/components/Launch/LaunchForm/LaunchFormInputs.tsx
src/components/Launch/LaunchForm/StructInput.tsx
src/components/Launch/LaunchForm/inputHelpers/constants.ts
src/components/Launch/LaunchForm/inputHelpers/getHelperForInput.ts
src/components/Launch/LaunchForm/inputHelpers/struct.ts
src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts
src/components/Launch/LaunchForm/inputHelpers/test/structTestCases.ts
src/components/Launch/LaunchForm/inputHelpers/test/testCases.ts
src/components/Launch/LaunchForm/inputHelpers/utils.ts
src/components/common/DumpJSON.tsx

This adds support for our `Struct` input type, which is essentially just a `Protobuf.Struct` object. Users will enter this value as a JSON object string, which will then be parsed and converted to a Protobuf.Struct object using the appropriate types for resulting values.
* Added inputHelper code for converting between a JSON object string and a `Struct` Literal.
* Updated code for type support to allow `Structs`.
* Added a component for entering a `Struct` value, which is similar to a `Collection` in that it is a multi-line string input.
* Added test cases, which involved some refactoring of the unit tests to correctly format the input values and expected outputs.
* Added a simple wrapper for `JSON.stringify` to ensure consistent formatting (2 spaces) and updated relevant code to use that …

feat: support Struct as a Launch input type

---

src/components/Executions/Tables/WorkflowExecutionsTable.tsx
src/components/Tables/DataList.tsx

When the last item in the list is larger than the default row size, appending more items to the list will cause the next item to bleed into the previously last item. This is because react-virtualized has the wrong value for the height of the row and hasn't been told to recompute it.
*Note*: There is no accompanying test for this change because testing the DataList component is prohibitively difficult due to the use of `CellMeasurer` and `Autosizer` from the `react-virtualized` package. I manually verified the fix.
When starting with a list of length `n`, the item at row index `n+1` is our "load more" row. We use a `CellMeasurerCache` to keep track of the heights of each row, and allow `react-virtualized` to computer the heights using a `CellMeasurer`. The starting height of the last row …

fix: recompute row heights when new items are appended to DataList

---

src/components/Executions/Tables/test/NodeExecutionsTable.test.tsx
src/components/Executions/Tables/useNodeExecutionsTableState.ts
src/components/common/DetailsPanel.tsx

Fixes an issue where status of a NodeExecution doesn't update in the DetailsPanel if you have the panel open when the status changes.
We were assigning the selected item for the Details Panel using an object reference, instead of an id reference. When the node executions update, new copies of the items are returned. But the DetailsPanel was still rendering the previously referenced object. To fix it, I updated the state tracking the selected item to be by id / cache key and am now computing the object to return using a memoized `find` call on the array of executions whenever the array or the selected id change.
Also added a test to cover the regression.
https://github.com/lyft/flyte/issues/505
_NA_

fix: stale selected item reference in NE details panel

---

src/components/Executions/ExecutionDetails/test/RelaunchExecutionForm.test.tsx
src/components/Executions/Tables/__stories__/NodeExecutionsTable.stories.tsx
src/components/Launch/LaunchForm/__stories__/LaunchForm.stories.tsx
src/components/Literals/RemoteLiteralMapViewer.tsx
src/components/Literals/test/RemoteLiteralMapViewer.test.tsx
src/models/Execution/api.ts
src/models/Execution/types.ts

Handle null LiteralMap in RemoteLiteralMapViewer
Not sure I completely understand how proto objects translate to JS objects. There are cases when `fullInputs` and `fullOutputs` are equal to null. Pull request adds a null check that complements the existing undefined check.

fix: handle null LiteralMap in RemoteLiteralMapViewer

---

src/common/formatters.ts
src/common/test/formatters.spec.ts

Fixed a display issue for [AWS-style cron expressions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions) using an integer day-of-week field. We need to parse those expressions using a one-based index.
https://github.com/lyft/flyte/issues/616
_NA_

fix: use one-based day of week for aws cron expressions

---

src/components/Launch/LaunchForm/inputHelpers/collection.ts
src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts

This change ensures that the empty array literal string (`"[]"`) is correctly converted to a `Core.ILiteral` collection with an empty `literals` property.
The original implementation incorrectly determined that an empty array literal string should be converted to a `None` type `Literal`. This is equivalent to passing `void`/`null` for the value, which is not correct. I updated the code to continue trying to parse the inner value (which will be an empty JS array), resulting in the proper `Literal` value being returned.
https://github.com/lyft/flyte/issues/533
_NA_

fix: convert empty array literals to empty collection literals

---

src/components/Navigation/ProjectSelector.tsx
src/components/Navigation/SearchableProjectList.tsx

Fixes a few small issues with the Project selector on the Project Details page:
1. React errors about duplicate keys when more than one project entry uses the same `name`. This can easily happen when copying a project to a new repository. The `id` field should be used to key the elements.
2. Projects with duplicate names are difficult to tell apart because the `id` and `description` are not shown. Now all entries will show a tooltip on hover with the inner `id` and `description`(or a default 'no description').
3. Fixed overflow issues in the selector for long project names.

fix: display issues with Project selector

---

src/components/Executions/TaskExecutionDetails/TaskExecutionNodes.tsx
src/components/hooks/useConditionalQuery.ts

Fixes a failure to load data in the TaskExecutionDetails view when coming from a page where the TaskExecution has already been loaded an is in a final state.
Also fixes a refresh issue with child NodeExecutions on that page.
The `enabled` flag on `useQuery` is meant to delay running a dependent query until data from the parent is available. We were abusing it a little bit by attempting to use it to return cached data from a query without running the query. A better implementation of this is to conditionally set the `staleTime` to `Infinity` and disable refetch in the case where we want to just use whatever cached data is available. This updates `useCondtionalQuery` to follow that logic.
Also fixed an issue where the NodeExecutions list on the TaskExecutionDetails page was not refreshing …

fix: failed data loading/refreshing in TaskExecutionDetails

---

src/components/Executions/ExecutionDetails/ExecutionDetails.tsx
src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
src/components/Executions/ExecutionDetails/ExecutionWorkflowGraph.tsx
src/components/Executions/TaskExecutionDetails/TaskExecutionDetails.tsx
src/components/Executions/TaskExecutionDetails/TaskExecutionNodes.tsx
src/components/common/WaitForQuery.tsx

lyft/flyte#673
This updates WaitForQuery to render no content by default on errors (it still logs to the console) and updates the few cases where we do want to show an error to pass in a `DataError` component.
This fixes cases where we have small areas of the UI showing huge `DataError` components because they were waiting on a query that failed.
Before
After

fix: default to not showing errors for WaitForQuery

---

.github/workflows/release.yml

Update CI Settings after migrating to flyteorg.
https://github.com/flyteorg/flyte/issues/688

fix: Update CI post migration

---

src/components/Navigation/UserInformation.tsx

Use `name` from `/me` response if `preferred_username` is null.
Not all OIdP providers fill in all user info fields. Google, we found, uses the `name` field but not the `preferred_username` field.
https://github.com/flyteorg/flyte/issues/657

fix: Use name if preferredUsername is empty

---

src/components/Executions/ExecutionDetails/test/RelaunchExecutionForm.test.tsx
src/components/Executions/useWorkflowExecution.ts

Fixes issue where recent changes made to `flyteadmin` were not being supported in UI. The use-case is when a user goes to relaunch a workflow, we now return raw/full inputs when the payload is small enough; this adds support for `fullInputs`
see: https://github.com/flyteorg/flyteadmin/commit/067dc911bae09ee73cfcc6d46a658aa9a1c1d7d1#diff-9b311b663f43eccf79220bfcae3a565ad26d83532c945f39cfc1f7ba029c22e3

fix: handle fullInputs for relaunch workflow

---

README.rst

Signed-off-by: aviaviavi <avipress@gmail.com>
This change updates the README to use cr.flyte.org domain for the `docker run` example.
I believe these unchecked ones are N/A, but please let me know if I'm mistaken!
This change updates the README to use cr.flyte.org domain for the `docker run` example. It doesn't affect anything else beyond where the example points.
_NA_
_NA_

Use cr.flyte.org endpoint for Docker run command in README

---

package.json
src/components/Executions/constants.ts
yarn.lock

Render recovered node execution status similarly to succeeded
https://github.com/flyteorg/flyte/issues/1151
_NA_

Render recovered node execution status

---

src/components/Launch/LaunchForm/SimpleInput.tsx
src/components/Launch/LaunchForm/constants.ts
src/components/Launch/LaunchForm/inputHelpers/getHelperForInput.ts
src/components/Launch/LaunchForm/inputHelpers/utils.ts
src/components/Launch/LaunchForm/types.ts
src/components/Launch/LaunchForm/utils.ts
src/models/Common/types.ts

Add enum type input in launch form
https://github.com/flyteorg/flyte/issues/1217
_NA_

Support enum input type in launch form

---

src/components/Executions/TaskExecutionsList/TaskExecutionDetails.tsx

Fixed the `unknown` is being present for both `start time` and `duration` in task details panel for nodes.
Added `last updated` to be shown instead if both of above fields are absent in API response.
Created a `fallback` option when `started_at` and `duration` fields are not present in the API response.
fixes https://github.com/flyteorg/flyte/issues/885
_NA_

fix: duration is not always calculated for task executions

---

src/components/Executions/utils.ts

I am working on the fix for https://github.com/flyteorg/flyte/issues/1085 and have identified where the workflow breaks. This change fixes the issue (short version: id's were being used as keys but their values were truncated and thus we had duplicates) however I am new to the code base and unclear on the implications of removing this ternary.  Where/why do we use `metadata` rather than `id`? 
Can someone with more context please take a look and help me understand if there are any edge cases I am missing here?
- [ X] Bug Fix
https://github.com/flyteorg/flyte/issues/1085

fix: this is rfc, do not deploy until resolved; details in comments

---

src/components/Launch/LaunchForm/StructInput.tsx

This PR repopulates the input values when relaunching a wf/task that has an input of type struct/dataclass/json type.
fixes https://github.com/flyteorg/flyte/issues/1418
_NA_

fix: repopulate struct input fields on relaunch form

---

src/components/Executions/ExecutionDetails/ExecutionDetailsAppBarContent.tsx

This hides recover button for the successful executions.
fixes https://github.com/flyteorg/flyte/issues/1416
_NA_

fix: hide recover button for successful executions

---

src/components/Entities/EntityDetails.tsx
src/components/Entities/EntityVersions.tsx
src/components/Executions/Tables/WorkflowVersionsTable.tsx
src/components/Tables/PaginatedDataList.tsx
src/components/Workflow/StaticGraphContainer.tsx
src/components/common/ContentContainer.tsx
src/components/flytegraph/ReactFlow/ReactFlowGraphComponent.tsx
src/components/flytegraph/ReactFlow/ReactFlowWrapper.tsx

Remove space between versions table and the bar chart and increase minimal height of execution list view in workflow details page.
- Remove space between versions table and bar chart when there are not enough versions
- Add some minimal height for executions list view
fixes https://github.com/flyteorg/flyte/issues/1517
_NA_

fix: polish workflow details page

---

src/components/Entities/EntityExecutionsBarChart.tsx
src/components/common/BarChart.tsx

Fix issue with bar chart ordering and tooltip is being displayed in wrong place when the page is scrolled down.
Updated the fetching executions logic and tooltip positioning mechanism.
NA
_NA_

fix: tooltip scrolling and bar chart ordering issue

---

src/components/Entities/EntityDetails.tsx
src/components/Entities/EntityDetailsHeader.tsx

Fix back navigation from workflow version details view.
Conditionally set the back url for the navigation bar.
NA
_NA_

fix: back navigation from version details view

---

src/components/Navigation/UserInformation.tsx
src/components/Navigation/VersionDisplayModal.tsx
src/components/hooks/useVersion.ts
src/models/Common/api.ts
src/models/Common/types.ts

This adds a way for users to view version information. To open this view users will click an "information" icon that will render a modal displaying a users current versions for UI, Admin and Platform.
fixes https://github.com/flyteorg/flyte/issues/1466
_NA_

feat: add version display

---

package.json
webpack.config.ts
yarn.lock

This PR makes MIME type for requests to /assets/main.js served as application/javascript
fixes https://github.com/flyteorg/flyte/issues/1735
_NA_

feat: explicitly define content type

---

src/components/Literals/RemoteLiteralMapViewer.tsx

This fix supports a recent change to admin where the default response for node_executions no longer defaults to type-blob.
The previous code would early exit if the value for blob was null.  Previously, FlyteAdmin would default to returning this value so this pattern was appropriate.  However, with the new change we now want to check if literalMap exists first and only progress to checking the blob if the literal map is null.
_NA_
_NA_

Changed the return order to prioritize literal maps over blobs

---

webpack.config.ts

This commit appends to https://github.com/flyteorg/flyteconsole/pull/235 but moves the `webpack-plugin-serve` middleware to apply to both prod and dev builds. 
Serve middleware sets the MIME type of main-[hash].js to `application/javascrtipt'.  This middleware was initially configured to apply to dev-only; this change applies it to both prod and dev builds.
https://github.com/flyteorg/flyteconsole/pull/235

Add correct mime type to headers

---

src/components/Executions/ExecutionDetails/RelaunchExecutionForm.tsx
src/components/Launch/LaunchForm/LaunchFormAdvancedInputs.tsx
src/components/Launch/LaunchForm/LaunchRoleInput.tsx
src/components/Launch/LaunchForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchForm/launchMachine.ts
src/components/Launch/LaunchForm/styles.ts
src/components/Launch/LaunchForm/types.ts
src/components/Launch/LaunchForm/useLaunchWorkflowFormState.ts
src/models/Execution/api.ts

Display the original execution IAM or k8s role under "advanced options" in the launch form. Roles can be changed according to the `launch plan` if it has auth role in it; users can edit those roles manually. This fix also adds additional functionality to the launch from with the support of Annotations and Labels
Make the `Advanced options` in relaunch form shows the original execution IAM or k8s role.
Also those roles could be changed according to the `launch plan` changes if it has auth role in it.
And user can edit those roles manually.
fixes https://github.com/flyteorg/flyte/issues/1737
_NA_

fix: auth role to be aligned with launch plan and be editable by user

---

src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
src/components/Executions/Tables/nodeExecutionColumns.tsx
src/components/Executions/Tables/test/NodeExecutionsTable.test.tsx
src/components/Executions/types.ts
src/components/Executions/useNodeExecutionDetails.ts
src/components/Executions/utils.ts
tsconfig.json

Signed-off-by: Fernando Diaz <fediazgon@gmail.com>
As described in https://github.com/flyteorg/flyte/issues/1242. UI should show readable names to the user instead of execution ids.
Currently, Flyte Console shows [NodeExecutionIdentifier#node_id](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/core/identifier.proto#L53) which can be auto-generated and not readable for the user. Instead, I propose to use (Compiled)[Node#id](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/core/workflow.proto#L103) which is usually set to a readable name and can be overriden the user (using `with_overrides(node_name=....`) in `flytekit-python` and `builder.apply(/*nodeId=*/...,...)` in `flytekit-java`.
I've also improved the lookup nodes code to also lookup for nodes inside …

minor: Use readable names for TaskNode display

---

README.rst
pull_request_template.md

Fixes https://github.com/flyteorg/flyte/issues/1865

fix: Update README with correct release procedure

---

src/components/Entities/EntityExecutionsBarChart.tsx
src/components/Launch/LaunchForm/getInputs.ts
src/components/Project/ProjectStatusBar.tsx
src/components/Project/ProjectWorkflows.tsx
src/components/Theme/colorSpectrum.ts
src/components/Theme/constants.ts
src/components/Workflow/SearchableWorkflowNameList.tsx
src/components/Workflow/__stories__/SearchableWorkflowNameList.stories.tsx
src/components/Workflow/types.ts
src/components/Workflow/useWorkflowInfoItem.ts
src/components/Workflow/useWorkflowInfoList.ts
src/components/common/SearchableList.tsx
src/components/common/Shimmer.tsx
src/models/__mocks__/sampleWorkflowNames.ts

Update workflow search UX.
Workflow search UX includes workflow names, last execution time, last 10 executions, inputs, outputs and description.
fixes https://github.com/flyteorg/flyte/issues/1623
_NA_

feat: update workflow search UX

---

src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
src/components/Executions/ExecutionDetails/ExecutionMetadataExtra.tsx
src/components/Executions/ExecutionDetails/constants.ts
src/components/Executions/ExecutionDetails/test/ExecutionMetadata.test.tsx
src/models/Launch/api.ts

Add advanced launch options to execution details page.
Add `Service Account`, `Raw Output Prefix`, and `Parallelism` to execution details page.
fixes https://github.com/flyteorg/flyte/issues/1761
_NA_

feat: add advanced launch options to execution details

---

src/components/Workflow/SearchableWorkflowNameList.tsx
src/components/Workflow/useWorkflowInfoItem.ts

Workflow new search UX performance issue fix.
Workflow new search UX performance issue fix.
Added debounce search and stale time for react query.
Changed key prop and use React memo for performance optimization.
_NA_
_NA_

fix: performance issue related to search

---

README.rst
env.js
src/components/flytegraph/ReactFlow/ReactFlowGraphComponent.tsx
src/config/types.ts
src/models/AdminEntity/AdminEntity.ts

This PR removes `DISABLE_AUTH`.
The reasoning behind this decision is that the app itself does not use this value and is simply pass along with requests to Admin as `withCredentials`. However, this value has consequence on the server side as it informs `Access-control`; specifically if cross domain cookies can be set which can cause issues when connecting to Admin (and has no affect otherwise). 
see: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
Edit:
- This PR also includes a minor fix for displaying nested graphs
Removes `DISABLE_AUTH` from flyteconsole.
_NA_
_NA_

feat: Remove disable auth var

---

README.rst

This updates the documentation with instructions for how to run flyteconsole locally (localhost). 
Updated docs
_NA_
_NA_

Added documentation for running docker from localhost

---

README.rst
env.js
package.json
src/client.tsx
src/components/Navigation/VersionDisplayModal.tsx
yarn.lock

This integrates Google Analytics into the console application.
fixes https://github.com/flyteorg/flyte/issues/1442
_NA_

feat: integrate analytics

---

output.log
src/components/Entities/EntityExecutions.tsx
src/components/Entities/EntityExecutionsBarChart.tsx
src/components/Executions/Tables/constants.ts
src/components/Executions/Tables/nodeExecutionColumns.tsx
src/components/Executions/Tables/styles.ts
src/components/Executions/Tables/test/NodeExecutionsTable.test.tsx
src/components/Project/ProjectExecutions.tsx
src/components/common/BarChart.tsx

Update node list view according to design.
Added executions bar chart to project executions view.
Update node list view according to design.
Added executions bar chart to project executions view.
fixes https://github.com/flyteorg/flyte/issues/1911
https://github.com/flyteorg/flyte/issues/1910

feat: update node list view and add executions bar chart

---

src/components/Executions/ExecutionDetails/RelaunchExecutionForm.tsx
src/components/Launch/LaunchForm/LaunchRoleInput.tsx
src/components/Launch/LaunchForm/LaunchTaskForm.tsx
src/components/Launch/LaunchForm/LaunchWorkflowForm.tsx
src/components/Launch/LaunchForm/constants.ts
src/components/Launch/LaunchForm/handlers.ts
src/components/Launch/LaunchForm/launchMachine.ts
src/components/Launch/LaunchForm/test/LaunchTaskForm.test.tsx
src/components/Launch/LaunchForm/types.ts
src/components/Launch/LaunchForm/useLaunchTaskFormState.ts
src/components/Launch/LaunchForm/useLaunchWorkflowFormState.ts
src/models/Execution/api.ts
src/models/Execution/types.ts

This PR adds support for `securityContext` in Admin requests.  Currently this feature is not fully rolled out but this change will support both `authRole` and `securityContext` during the migration to prevent any breaking changes. The change will appear on Launch/Relaunch/Recover actions. This change also removes the either/or toggle between K8 and IAM roles - now users can enter both/either/none. 
see: https://github.com/flyteorg/flyteidl/blob/f4809c1a52073ec80de41be109bccc6331cdbac3/protos/flyteidl/core/security.proto#L111
FlyteAdmin is planning to migrate to using `securityContext` in the future however to support older versions of Admin we will send and receive both values for the time being.
_NA_
_NA_

feat: Add support for securityContext in launch form.

---

src/components/Executions/ExecutionDetails/ExecutionMetadataExtra.tsx
src/components/Executions/ExecutionDetails/constants.ts

This fix addresses a bug where authRole values would be missing from ExecutionData header.  This fix also includes adding both IAM and k8 values. 
Values for authRole of an execution will not be returned with getLaunchPlan(); this fix correctly uses the execution.spec to populate those values.
_NA_
_NA_

Fix: Fixed missing Authrole values on ExecutionMetaDataExtra

---

package.json
src/components/Executions/constants.ts
yarn.lock

Workflow executions now transition from 'running' -> 'aborting' -> 'aborted'. This change handles rendering the 'aborting' phase.
Note: I wasn't sure whether it was worth updating the [workflow status filters](https://github.com/flyteorg/flyteconsole/blob/master/src/components/Executions/filters/statusFilters.ts#L7) since this phase is transitive and ideally short-lived
See linked issue below.
https://github.com/flyteorg/flyte/issues/1978
_NA_

feat: handle 'Aborting' workflow execution phases

---

src/components/Entities/EntityVersions.tsx

[BUG-2065](https://github.com/flyteorg/flyte/issues/2065)
This fixes a bug in the recent workflow versions table when filtering executions.

fix: recent workflow bug on filtering executions

---

CONTRIBUTING.md
README.md
src/basics/FeatureFlags/FeatureFlags.test.tsx
src/basics/FeatureFlags/defaultConfig.ts
src/basics/FeatureFlags/index.tsx
src/common/env.ts
src/components/App/App.tsx
src/components/Executions/Tables/styles.ts
src/components/Executions/Tables/useWorkflowExecutionsTableColumns.tsx
src/components/Theme/muiTheme.ts
src/config/types.ts

This PR adds FeatureFlags support. 
I decided to add it now, to avoid/minimize merge conflicts related to adding "Launch Plan" button into workflow execution list.
Feature preview: [https://share.getcloudapp.com/kpu4NOlJ](https://share.getcloudapp.com/kpu4NOlJ)
With feature flags support:
- we can iterate with smaller PRs and enable features for end users when they are fully tested, while allow testing for other devs during development process.
- It allows to avoid massive merge conflicts, which are often created if features are fully developed and contained in separate branches until they are release ready.
In future if product will grow it will allow us to easily switch to any Feature Flag provider, to allow A/B testing and feature rollout.

chore: feature flags support for parallel development

---

.eslintrc.js
src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
src/components/Executions/ExecutionDetails/test/ExecutionDetailsAppBarContent.test.tsx
src/components/Executions/ExecutionDetails/test/RelaunchExecutionForm.test.tsx
src/components/Executions/Tables/test/NodeExecutionsTable.test.tsx
src/components/Executions/useNodeExecutionDetails.ts
src/components/Launch/LaunchForm/LaunchFormAdvancedInputs.tsx
src/components/Launch/LaunchForm/SimpleInput.tsx
src/components/Launch/LaunchForm/StructInput.tsx
src/components/Launch/LaunchForm/inputHelpers/test/utils.test.ts
src/components/Launch/LaunchForm/test/LaunchTaskForm.test.tsx
src/components/Launch/LaunchForm/utils.ts
src/components/Literals/Scalar/ProtobufStructValue.tsx
src/components/Notifications/SystemStatusBanner.tsx
src/components/common/Shimmer.tsx
src/components/common/__stories__/ButtonCircularProgress.stories.tsx
src/components/common/test/MoreOptionsMenu.test.tsx
src/components/common/test/SearchableList.spec.tsx
src/components/flytegraph/ReactFlow/customNodeComponents.tsx
src/components/hooks/__mocks__/fetchableData.ts
src/components/hooks/test/useFetchableData.test.tsx
src/components/hooks/test/utils.test.ts
src/models/AdminEntity/AdminEntity.ts
src/models/Graph/types.ts
src/models/Node/types.ts

**No code changes, only cleanup of unused code, or ensuring that tests are valid**
Cleanup some eslint rules violation, which allowed as to
- remove **no-case-declarations** rule
- remove **'jest/valid-title'** rule
- go down from 393 to 357 current warnings in repo
- added all warning implicitly with their count in code
In future we would be able to move to more modern rules and code practices.

chore: cleanup eslint rules

---

src/basics/LocalCache/defaultConfig.ts
src/basics/LocalCache/index.tsx
src/basics/LocalCache/localCache.test.tsx
src/components/Entities/EntityDescription.tsx
src/components/Entities/EntityDetails.tsx
src/components/Entities/EntityDetailsHeader.tsx
src/components/Entities/EntitySchedules.tsx
src/components/Entities/EntityVersions.tsx
src/components/Entities/constants.ts
src/components/Entities/strings.ts
src/components/Entities/test/EntitySchedules.test.tsx
src/components/Workflow/WorkflowVersionDetails.tsx

In workflow view we now allow user to collapse/expand workflow versions section. User choice would be persistent between pages (by LocalStorage)
video: https://share.getcloudapp.com/kpu4e0l1
- Added useLocalCache hook, which uses local storage to persist user settings
-  Uncoupled EntityDetails page from WorkflowVersionDetailsContainer. Now they are independent pages
- Moved "Launch[Entity]" form into EntityDetailsHeader, so it will leave along side "Launch[Entity]" button.
fixes https://github.com/flyteorg/flyteconsole/issues/281

feat(#281): allow to collapse/expand workflow version section   #patch

---

src/components/Executions/Tables/nodeExecutionColumns.tsx

Wrap text with ellipsis if it's too long, and add Tooltip, so we can still see whole display-id.
**Most changes a whitespace only**, I marked the fix with a comment
Prior to the fix:
After the fix:
The main point described in issue 292 was fixed in flyteconsole v.0.42.1
The only issue left - was nodeId is not fully readable and obscuring the view, in case if id is too long to fit into a cell. This PR fixes it.
fixes https://github.com/flyteorg/flyteconsole/issues/292

fix: long node-id obscures task type #patch

---

src/basics/FeatureFlags/defaultConfig.ts
src/basics/LocalCache/defaultConfig.ts
src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx

This PR enables Timeline view on workflow execution page for everyone. 
All guarding feature flags are removed.
fixes https://github.com/flyteorg/flyteconsole/issues/302

feat: enable timeline view

---

package.json
src/components/common/BarChart.tsx
src/components/common/__stories__/BarChart.stories.tsx
src/components/hooks/useFetchableData.ts
src/models/AdminEntity/transformRequestError.ts
yarn.lock

This PR:
- updates typescript to v. 4.6.2 and fixes typing issues raised along.
- fixes chartBar regression, by showing up tooltip when user hover on top of individual bars.
During testing I found a bug, that the BarChart doesn't show the tooltip anymore. Tested this component due to typings changes required in getBoundingClientRect() function which is used by BarChartItem.
I looked into Demo site, and found that we are not showing up a tooltip for quite a time now.
fixes https://github.com/flyteorg/flyteconsole/issues/339

fix(bug_339): show tooltip on chart bars hover

---

.storybook/preview.js
jest.config.js
src/components/Errors/__stories__/DataError.stories.tsx
src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
src/components/Executions/Tables/__stories__/NodeExecutionsTable.stories.tsx
src/components/Executions/TaskExecutionsList/TaskExecutionLogs.tsx
src/components/Executions/TaskExecutionsList/TaskExecutionsListItem.tsx
src/components/Executions/constants.ts
src/components/Executions/contextProvider/NodeExecutionDetails/createExecutionArray.tsx
src/components/Executions/contextProvider/NodeExecutionDetails/getTaskThroughExecution.ts
src/components/Executions/types.ts
src/components/Executions/utils.ts
src/components/Notifications/__stories__/SystemStatusBanner.stories.tsx
src/components/Theme/constants.ts
src/components/WorkflowGraph/WorkflowGraph.tsx
src/components/WorkflowGraph/transformerWorkflowToDag.tsx
src/components/common/MapTaskExecutionsList/MapTaskStatusInfo.stories.tsx
src/components/common/MapTaskExecutionsList/MapTaskStatusInfo.test.tsx
src/components/common/MapTaskExecutionsList/MapTaskStatusInfo.tsx
src/components/common/__stories__/Decorators.tsx
src/components/common/__stories__/Typography.stories.tsx
src/components/flytegraph/ReactFlow/ReactFlowGraphComponent.tsx
src/components/flytegraph/ReactFlow/ReactFlowWrapper.tsx
src/components/flytegraph/ReactFlow/transformDAGToReactFlowV2.tsx
src/components/flytegraph/constants.ts
src/components/flytegraph/layoutUtils.ts
src/components/flytegraph/utils.ts
src/models/Task/constants.ts
src/models/Task/task.test.ts
src/models/Task/utils.ts

This PR adds some side cleaning of our code and adds a simple component to show logs for Map tasks
The feature work would be done in separate PR and should be much easier to check with this data being out of the way.
PR covers:
- Adding current typography preview to Storybook
- Ensure that storybook first will show Primitives and Common folders, and than everything else
- Remove single story folders from Storybook
- Remove duplicated debug logger "implementation" from utils file. Now it always would be imported from 'common/log';
- Added two common task types which should be always interpreted as arrays in flyteconsole: `aws-batch` and `k8s-array`
- Ensure that tasks always use proper DisplayType in Node and TaskDetailsPanel view. Graph view will always use taskType from data - as it does …

chore: fix TaskType display to ensure consistency, code cleanup, add mapTaskListItem component

---

.eslintrc.js
src/components/Entities/EntitySchedules.tsx
src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
src/components/Navigation/VersionDisplayModal.tsx
src/components/Project/ProjectExecutions.tsx
src/components/SelectProject/ProjectList.tsx
src/components/Tables/LoadMoreRowContent.tsx
src/components/common/DetailsPanel.tsx
src/components/common/ErrorBoundary.tsx
src/components/common/ExpandableContentLink.tsx
src/components/common/__stories__/BarChart.stories.tsx
src/components/flytegraph/InteractiveViewBox.tsx
src/components/flytegraph/ReactFlow/NodeStatusLegend.tsx
src/components/flytegraph/RenderedGraph.tsx
src/models/AdminEntity/types.ts
src/models/Common/types.ts
src/models/Execution/enums.ts
src/models/Launch/types.ts

Updated some eslint rules settings, to ensure more accurate erroring. 
Fixed errors which were not required more detailed testing:
- Updated `no-unused-vars` and `no-redeclare` to typescript versions
- Allowed to break `camelcase` and `jsx-a11y/*` rules in **test** and **storybook** files
- removed some unused variables, which was obviously not in use (left in place those which require some investigation)
- removed unused exports for Props interfaces (we should limit export usage only if type is needed to be reused - it minimizes release package size)
- moved render functions to the end of class ( in two places) - no code change
- disabled `no-redeclare` rule for enum declarations

chore: cleaning up eslint rules

---

src/components/Executions/ExecutionDetails/ExecutionWorkflowGraph.tsx
src/components/Executions/nodeExecutionQueries.ts
src/components/WorkflowGraph/WorkflowGraph.tsx
src/components/flytegraph/ReactFlow/ReactFlowGraphComponent.tsx
src/components/flytegraph/ReactFlow/transformDAGToReactFlowV2.tsx

This fixes a bug where tasks were not correctly rendered in the graph.  The issue stems from an incorrect assumption that a `NodeExecution.nodeId` was the correct key to map against `CompiledWorkflowClosure` but in fact we must key off `scopedId`. 
Note: this is WIP pending regression testing.
fixes https://github.com/flyteorg/flyteconsole/issues/333
_NA_

fix: Changed memo filter to scopedId from node.id

---

src/common/constants.ts
src/components/Task/SearchableTaskNameList.tsx
src/components/Workflow/SearchableWorkflowNameList.tsx

Workflow and task descriptions aren't properly populating due to issues on the backend, while they are being addressed, empty description string should not be rendered.
Workflows
Tasks

fix: stop displaying empty descriptions

---

src/components/Launch/LaunchForm/useLaunchWorkflowFormState.ts

Current Behavior is to fetch only 10 launch-plans per workflow . This causes issues for users who have > 10 launch-plans with no way of fetching/triggering them via the UI.

fix: Bump list launch-plans limit=50 #patch

---

webpack.config.ts

Moved Jason's fix from his POC one click PR:
https://github.com/unionai/flyteconsole/pull/1/files#diff-ec2cabc8139e814d33682814c1ba15a1056d946ab70f740c9d42ada07af42050
fixes https://github.com/flyteorg/flyteconsole/issues/359

fix(359): fix assets folder location to simplify oneclick experience

---

src/components/Entities/EntityDetailsHeader.tsx
src/components/Executions/ExecutionDetails/NodeExecutionTabs/index.tsx
src/components/Executions/ExecutionDetails/Timeline/BarChart/utils.ts
src/components/Executions/TaskExecutionsList/MapTaskExecutionListItem.tsx
src/components/Executions/TaskExecutionsList/TaskExecutionLogs.tsx
src/components/Executions/TaskExecutionsList/TaskExecutions.mocks.ts
src/components/Executions/TaskExecutionsList/TaskExecutionsList.tsx
src/components/Executions/TaskExecutionsList/TaskExecutionsListContent.stories.tsx
src/components/Executions/TaskExecutionsList/test/utils.spec.ts
src/components/Executions/TaskExecutionsList/utils.ts
src/components/common/MapTaskExecutionsList/MapTaskStatusInfo.stories.tsx
src/components/common/MapTaskExecutionsList/MapTaskStatusInfo.test.tsx
src/components/common/MapTaskExecutionsList/MapTaskStatusInfo.tsx
src/flyteidl/index.ts

Allow to support new MapTask structure, where individual logs are grouped by current phase status.
fixes https://github.com/flyteorg/flyteconsole/issues/310
Map tasks completed before Admin update have old look:
Task completed after admin Update have new look:
Added Storybook implementations:
In storybook below you can see all possible data shown. Log items rendered as lighter black text - are the ones that don't yet have logs links assigned

feat(310): map task v1 visuals, supporting both old and new api

---

webpack.config.ts

This reverts commit 9d1a5f83c256e3265c0d02d41038335ddd5eb948.
We need to figure out why production build is not working with assets folder change

Revert "fix(359): fix assets folder location to simplify oneclick experience (#360)" #patch

---

src/components/Executions/Tables/WorkflowExecutionTable/WorkflowExecutionRow.tsx
src/components/Executions/Tables/WorkflowExecutionTable/styles.ts

In the execution table, the cancel button is overflowing, and half of the text can't be seen. Also, the duration data is not rendered. 
what it looks like now. 
Added back the duration data to render in the row 
Fixed the width for the Confirmation Buttons. Use % for width, so it won't overflow 
fixes https://github.com/flyteorg/flyteconsole/issues/367

Fix Confirmation Buttons Overflow on Execution Table

---

index.js
webpack.config.ts

Previous version still had an assets folder pre-build to dist folder.

Fix: ensure that assets are not in a hashed folder

---

src/components/Executions/Tables/styles.ts
src/components/Tables/DataList.tsx
src/components/Tables/constants.ts

Signed-off-by: Eugene Jahn <eugenejahnjahn@gmail.com>
fixed this issue https://github.com/flyteorg/flyteconsole/issues/318
btw. I have updated the issue to address another responsive bug for the table. It's also fixed. 
removed `flex-grow: 0` and `flex-shrink:0` on the table column. We don't need it because we want the table to be responsive. Otherwise, can't show data in the smaller width window. 
also, set a minHeight for the table rows container. Otherwise, the height of the row container will be set to 0 due to auto resizer.  
fixes: https://github.com/flyteorg/flyteconsole/issues/318
_NA_

fix: on resize Header and body of the tables are mismatched

---

src/models/AdminEntity/transformRequestError.ts

Signed-off-by: eugenejahn <eugenejahnjahn@gmail.com>
Not sure should I suppose to fix this...  I was trying to fix  https://github.com/flyteorg/flyteconsole/issues/336, but kind of annoyed by not seeing the error message, so I just fix it. (may not be 100% complete)
Enrich the error message. In launch form, users should see a complete error message from the API response 
After fixed: 
I decoded the response from the api and return it as new error. However, one thing I am not quite sure is do we have a decode type for the error message? now, I am just using RawOutputDataConfig type to decode...
also since I don't think we will use decodeErrorResponseMessage in other place, I didn't put in ./utils. Let me know if you want me to put into utils. 
fixes …

fix: add more descriptive errors on task/workflow run failure

---

src/components/Executions/Tables/WorkflowExecutionTable/cells.tsx
src/components/Project/ProjectWorkflows.tsx
src/components/Project/test/ProjectWorkflows.test.tsx
src/components/Workflow/SearchableWorkflowNameList.tsx
src/components/Workflow/__stories__/SearchableWorkflowNameList.stories.tsx
src/components/Workflow/filters/useWorkflowShowArchivedState.ts
src/components/Workflow/types.ts
src/components/Workflow/useWorkflowInfoList.ts
src/components/Workflow/utils.ts
src/models/Workflow/api.ts
src/models/Workflow/enums.ts
src/models/__mocks__/sampleWorkflowNames.ts

New feature: Archive/Unarchive workflows
Archive Button: https://share.getcloudapp.com/d5u9nvpy
Archive Actions: https://share.getcloudapp.com/p9u6Q7r2
Allows to filter workflows by archive state in the console, and for individual workflows to be archived/unarchived
Added WorkflowExecutionState enum and calls to NamedEntityUpdate
Added notistack to support error and success notifications
Ensured that items could be archived and unarchived from "workflow" 
Updates storybook to observe all recent changes
Added "localization" string support
adds feature for https://github.com/flyteorg/flyteconsole/issues/320

feat: Allow to archive workflow from flyteconsole

---

src/components/Launch/LaunchForm/BlobInput.tsx

Signed-off-by: Eugene Jahn <eugenejahnjahn@gmail.com>
fix dimensionality per data type blob and be disabled in UI. For the blob input, we will set the dimensionality based on the blob type(if dimensionality from blob type is empty, we set to BlobDimensionality.SINGLE)
add the dimensionality from typeDefinition?.literalType?.blob?.dimensionality
disable the select component 
fixes https://github.com/flyteorg/flyteconsole/issues/336

fix: dimensionality per data type blob and be disabled in UI

---

src/components/Executions/ExecutionDetails/ExecutionMetadataExtra.tsx
src/models/Execution/api.ts

Signed-off-by: eugenejahn <eugenejahnjahn@gmail.com>
Service account is not properly propagated from the execution info
should fix the issue, but can't reproduce the demo bug. so not 100% sure the results. let me know if the code is not working 
fixes https://github.com/flyteorg/flyteconsole/issues/372
_NA_
OR

fix: service account is not properly propagated from the execution info

---

src/components/Project/ProjectDashboard.tsx

Now Project domain page for flytecsnacks looks like:
Added NONE limit to request which is currently corresponds to 10000 items. 
We requested  a new API from backend to return total number of items, which is tracked by https://github.com/flyteorg/flyteconsole/issues/382
fixes https://github.com/flyteorg/flyteconsole/issues/383

fix(383): tasks and workflow number capped to 25 in dashboard page

---

src/components/Workflow/workflowQueries.ts
src/components/WorkflowGraph/WorkflowGraph.tsx

Current fix removed request for undefined executionIds, which usually happens with branch nodes.
It allows us to avoid unneeded crash. Further work is needed for proper support of Branch nodes.
fixes https://github.com/flyteorg/flyteconsole/issues/378
This fix currently removes the crash, however it doesn't fix the branch node representation, which is still a bit off. A separate task was created to cover that work: 
https://github.com/flyteorg/flyteconsole/issues/377
`TODO` with task number was added to the code to ensure, that fix would be fully tested

fix(378): ensure that undefined executions ids won't get into graph

---

.github/workflows/checks.yml

Currently on merge to master we run the ` Build & Push Flyteconsole Image` github action twice: one instance only builds the docker image and the second instance builds and pushes it.
This change makes it so we build the image on open PRs and build and push the image on merges.
_NA_
_NA_

chore: remove redundant docker build on merge to master

---

.github/workflows/checks.yml

Reverts flyteorg/flyteconsole#390
sequence of steps is
1. build image successfully
2. release flyteconsole
3. build & push image

Revert "chore: remove redundant docker build on merge to master"

---

.storybook/StorybookContainer.tsx
src/components/Executions/ExecutionDetails/Timeline/TimelineChart/utils.ts
src/components/Executions/ExecutionDetails/test/TimelineChart.test.tsx
src/components/Executions/Tables/__stories__/WorkflowExecutionsTable.stories.tsx
src/components/Launch/LaunchForm/useLaunchTaskFormState.ts
src/components/Launch/LaunchForm/useLaunchWorkflowFormState.ts
src/components/Workflow/__stories__/SearchableWorkflowNameList.stories.tsx
src/models/Execution/api.ts

Left over cleanup which wasn't connected to previous PR.
- Moved `SnackbarProvider` to default storybook wrappers
- Removed `RelationToCache` as it was never used
- Removed `getOffsetColor`, and tests for it, as we stop using it some time ago
- Removed `authRole` from `createWorkflowExecution` as we haven't really used this variable.
Tested locally by:
- Running new Workflow and Task execution
- Re-running Workflow and task execution by using "Relaunch"
- Run `yarn test`
- Ensured that storybook still can show error snackbar notification on archive/unarchive

chore: cleanup of unused variables

---

index.js
webpack.config.ts

We had an issue raised by one of our users who had different domains for console and admin api.
In his case all  Admin API request performed at `ui_domain/console` where navigated to `ui_domain/api/v1/request` instead of `admin_api/api/v1/request`. 
However if request performed from any other page , for example `domain/console/projects/flytectldemo/workflows` it will work as expect.
This change adds back `/assets` folder to hold  main.js and vendor.js and puts assets at the same  `/assets` folder
_NA_
OR

Fix: assets path for index.js query

---

src/components/SelectProject/ProjectList.tsx

Before we introduces ProjectDashboard page, the most top level view was Workflows page, so navigating to it was a logical decision.
Now it is more logical to navigate user to ProjectDashboard page for selected peoject/domain from  project list selection `/console` section.
Video with the fix: https://share.getcloudapp.com/8LuDNkBr

fix: on project select navigate to corresponding ProjectDashboard

---

yarn.lock

Fixes Severe security issue (9.8 / 10): Prototype pollution in `minimist`.
This fix, ensures that we stop using mkdirp@0.5.1  which came through favicons@6.2.2, and instead allow to use a version (0.5.5) which doesn't depend on minimist package

ci: update lowest mkdirp version

---

README.md

Signed-off-by: Haytham Abuelfutuh <haytham@afutuh.com>
Release 1.0.0
https://github.com/flyteorg/flyte/issues/2396

chore: Release 1.0 #major

---

packages/plugins/components/package.json
packages/plugins/components/src/NavBar/index.tsx
packages/plugins/components/src/NavBar/navbar.stories.tsx
packages/plugins/components/tsconfig.build.json
packages/zapp/console/tsconfig.build.json
packages/zapp/console/tsconfig.json
tsconfig.base.json

This PR separates default config used from build config to:
- ensure that VSCode IntelliSence will properly map files
- builds will still exclude test / stories / mock files.
In this PR I checked and fixed "tsc" builds - which is used for plugins (and will be used for most other packages)
It DOES NOT include proper build config usage for webpack, yet. It shouould be done separately
part of https://github.com/flyteorg/flyteconsole/issues/431

chore(tsc): exclude test/stories/mock files only from build

---

packages/zapp/console/tsconfig.json
packages/zapp/console/webpack.common.config.ts

[The previous PR ](https://github.com/flyteorg/flyteconsole/pull/451) prepared a base and ensured of proper build through TSC (libs, microapp, npm packages). It made sure that tasks / mocks/ specs won't be included in final build. 
This PR finishes exclude pattern for webpack.
part of https://github.com/flyteorg/flyteconsole/issues/431

ci: ensure that webpack too doesn't include test/mock/specs files

---

packages/zapp/console/src/components/hooks/useVersion.ts

Previous version sliced out the last symbol if version didn't have `-xx` postfix. 
In real live we still want to show postfix in the version.
Fixed:

fix: ensure that admin version is fully shown

---

README.md

This PR updates the readme file to help users deal with OSX dropping python support.
_NA_
_NA_
_NA_

Updated README to include instructions for OSX python support

---

packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionWorkflowGraph.tsx
packages/zapp/console/src/components/Executions/TaskExecutionsList/TaskExecutionsList.tsx
packages/zapp/console/src/components/WorkflowGraph/test/WorkflowGraph.test.tsx
packages/zapp/console/src/models/Task/task.test.ts
packages/zapp/console/src/models/Task/utils.ts

Added event version check to show new map task UI (graph and details tab) only for events with version >= 1.
With eventVersion
Without eventVersion
fixes https://github.com/flyteorg/flyteconsole/issues/381
_NA_

fix: add eventVersion check for map tasks

---

package.json
yarn.lock

We currently using favicon package to genereate icons and put them into assets folder.
"favicons": "^6.2.0",
"favicons-webpack-plugin": "^5.0.2",
Favicon v. 6.2.2 was release more than a year ago and leads to hardcoded mkdirp@0.5.1 which leads to minimist@0.0.8 with severe vulnerability.
Newer favicon version 7.0.0-beta is not compattible with favicons-webpack-plugin.
We need to investigate (https://github.com/flyteorg/flyteconsole/issues/491):
- if better package is available for this need.
- if we can minimize amount of generated icons, as currently we have a lot of sizes we don't really need.
https://github.com/flyteorg/flyteconsole/issues/491

fix: resolve minimist package to v1.2.6

---

.storybook/main.js
jest.config.js
packages/plugins/flyte-api/README.md
packages/plugins/flyte-api/jest.config.js
packages/plugins/flyte-api/package.json
packages/plugins/flyte-api/src/Sample/index.tsx
packages/plugins/flyte-api/src/Sample/sample.stories.tsx
packages/plugins/flyte-api/src/Sample/sample.test.tsx
packages/plugins/flyte-api/src/index.ts
packages/plugins/flyte-api/tsconfig.build.json
packages/plugins/flyte-api/tsconfig.json
packages/zapp/console/src/routes/NavBarRouter.tsx
packages/zapp/console/tsconfig.json
packages/zapp/console/webpack.common.config.ts

It's a boilerplate PR, which adds a separate plugin package for further Auth + FlyteAPI calls support

ci: add flyte-api plugin package

---

.github/workflows/checks.yml

- Fix ci job output name
Test: https://github.com/evalsocket/flyteconsole/actions/runs/2351058970
_NA_
OR

hotfix ci pipeline

---

packages/zapp/console/package.json
packages/zapp/console/src/components/Executions/filters/startTimeFilters.ts
yarn.lock

With one of the updates of moment version, new d.ts file implementation came by, which required moment to be imported using * as syntax
```
import * as moment from 'moment'
```
Without it the moment wasn't recognized as a function and as result all filtering failed.
fixes https://github.com/flyteorg/flyteconsole/issues/508

fix(bug-508): executions can not be filtered by start time

---

packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions.tsx

Null-ref when switching between node executions due to race condition.
When clicking through node executions, a race condition happens for the current execution data, leading to us trying to access properties on the details object that do not exist.
fixes https://github.com/flyteorg/flyteconsole/issues/505

fix: cannot read properties of undefined

---

packages/zapp/console/src/components/Navigation/NavigationDropdown.tsx
packages/zapp/console/src/components/Navigation/Readme.md

Updated Readme
Treat all url as external - needed for proper navigation between two apps located at the same client domain, but under different paths.
User needs to add `+` sign to the url which need to be treated as internal once (to avoid full application refresh).
Signed-off-by: Nastya <55718143+anrusina@users.noreply.github.com>

chore: support internal/external navigsation better

---

packages/zapp/console/src/components/Navigation/DefaultAppBarContent.tsx
packages/zapp/console/src/components/Navigation/NavBar.tsx
packages/zapp/console/src/components/Navigation/NavigationDropdown.tsx
packages/zapp/console/src/components/Navigation/Readme.md
packages/zapp/console/src/components/Navigation/utils.ts

Updated FLYTE_NAVIGATION related Readme.md
Allow to change default "Console" option name
Signed-off-by: Work <awork@narusina.fritz.box>

chore: update navigationDropdown usage

---

packages/zapp/console/src/components/Executions/ExecutionDetails/RelaunchExecutionForm.tsx
packages/zapp/console/src/components/Launch/LaunchForm/LaunchWorkflowForm.tsx
packages/zapp/console/src/components/Launch/LaunchForm/types.ts

Use execution security context in Relaunch form
Derived execution security context into Relaunch form
fixes https://github.com/flyteorg/flyte/issues/496

fix: Relaunch form does not persist security context values when changed

---

packages/zapp/console/src/components/Executions/TaskExecutionsList/test/TaskExecutionDetails.test.tsx

Ideally we should replace this test and other time sensitive tests with fake clock system.
For now bumping years ago expectation

test: fix time sensitive test

---

packages/zapp/console/src/components/Launch/LaunchForm/LaunchFormInputs.tsx
packages/zapp/console/src/components/Launch/LaunchForm/MapInput.tsx
packages/zapp/console/src/components/Launch/LaunchForm/__mocks__/utils.ts
packages/zapp/console/src/components/Launch/LaunchForm/__stories__/MapInput.stories.tsx
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/getHelperForInput.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/map.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/test/testCases.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/test/utils.test.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/utils.ts
packages/zapp/console/src/components/Launch/LaunchForm/test/constants.ts
packages/zapp/console/src/components/Launch/LaunchForm/utils.ts
packages/zapp/console/src/components/common/strings.ts
yarn.lock

This issue is to add support for mapped tasks to the Launch Form UX. While mapped tasks are most often one-dimensional (eg, k:v) flyte supports nested mapping (n-dimensional) as well. To support both use-cases we will provide UX that will renders a standard input field for 1D mappings and a text area (eg, where users can paste JSON text) for n-D mappings.
https://user-images.githubusercontent.com/105876962/175947368-c69d07a8-c4b4-410f-b0e8-6291e32afcd0.mov
Map type was unsupported and there were no inputHelpers for MAP. I added those helpers and enabled the Map type to be supported. The UI is like the above video
fixes https://github.com/flyteorg/flyteconsole/issues/483

fix: support mapped tasks

---

packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions.tsx
packages/zapp/console/src/components/Executions/Tables/NodeExecutionActions.tsx

Ensured task input types are retrieved properly before trying to prepare initial parameters for `NodeExecutionActions` relaunch form.
Similar as with `ExecutionDetailsActions`, a race condition exists when expanding `NodeExecutionActions` - the task and its input types are sometimes not loaded properly, resulting in an [(unchecked) access](https://github.com/flyteorg/flyteconsole/blob/devmain/packages/zapp/console/src/components/Launch/LaunchForm/utils.ts#L205) to retrieve an input's type.
#506 already fixed this race condition for the `ExecutionDetailsActions`, this PR applies the identical change to the `NodeExecutionActions`.
I've based this PR against `devmain` instead of `master` as the other fix has been applied there as well - can rebase if needed. Tests seem to be failing …

Fixed undefined task input types access in NodeExecutionActions

---

packages/zapp/console/src/components/Launch/LaunchForm/LaunchFormInputs.tsx
packages/zapp/console/src/components/Launch/LaunchForm/SimpleInput.tsx
packages/zapp/console/src/components/Launch/LaunchForm/UnionInput.tsx
packages/zapp/console/src/components/Launch/LaunchForm/constants.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/getHelperForInput.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/union.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/utils.ts
packages/zapp/console/src/components/Launch/LaunchForm/types.ts
packages/zapp/console/src/components/Launch/LaunchForm/utils.ts
packages/zapp/console/src/components/common/strings.ts

Signed-off-by: eugenejahn <eugenejahnjahn@gmail.com>
Support the Union Type in launch form and task input.  
Here is the example: https://localhost.demo.nuclyde.io:3000/projects/uxsandbox/domains/development/workflows/unionTypeExample.wf?duration=all
fixes https://github.com/flyteorg/flyteconsole/issues/536
fixes https://github.com/flyteorg/flyteconsole/issues/499

feat: support union type for launch plan

---

packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionWorkflowGraph.tsx
packages/zapp/console/src/components/Executions/nodeExecutionQueries.ts

Executions with nested elements have realtime update in Graph view as execution progresses.
Nested elements were not getting a proper data update during execution progress, as the check was looking at fields, while the target element was still wrapped in array, so all those nodes had stale data, which made an impression that graph is not reflecting the progress. Fixing this problem uncovered a React issue with hooks in `ExecutionWorkflowGraph` which resulted in the rewrite around the data fetch.
Demo: https://user-images.githubusercontent.com/101579322/179275092-b9e803bc-8bbb-4e75-8299-e6d1ae4bc364.mov
fixes https://github.com/flyteorg/flyteconsole/issues/523
_NA_

fix: graph has realtime updates as execution progresses

---

packages/zapp/console/src/components/Executions/nodeExecutionQueries.ts

Fix to make sure graph without nested groups aren't failing to display.
Before
After
_NA_

fix: make sure groups used in graph aren't undefined

---

.github/workflows/checks.yml
.github/workflows/upgrade_automation.yml
boilerplate/update.cfg

The root cause of CI pipeline failure:
- In flyteconsole, we are not creating a release for each merge, Release will depend on the PR title. Meaning in our CI [this step](https://github.com/flyteorg/flyteconsole/blob/28a224e7ef800f33ecc754835aceb90f8c0cff0b/.github/workflows/checks.yml#L109) will always run but will not produce any output because each master merge doesn't have a tag. 
Empty tags are responsible for the CI pipeline failure https://github.com/flyteorg/flyteconsole/runs/7434395445?check_suite_focus=true
Test: 
For a release: https://github.com/evalsocket/flyteconsole/runs/7464756361?check_suite_focus=true#step:4:9
for a normal commit: https://github.com/evalsocket/flyteconsole/actions/runs/2717297519
_How did you fix the bug, make the feature etc. Link to any design docs …

fix: flyteconsole tag in ci pipeline 

---

packages/zapp/console/src/components/LaunchPlan/SearchableLaunchPlanNameList.tsx
packages/zapp/console/src/components/Literals/__stories__/helpers/typeGenerators.ts
packages/zapp/console/src/components/Literals/test/helpers/mock_simpleTypes.ts
packages/zapp/console/src/components/Workflow/SearchableWorkflowNameList.tsx
packages/zapp/console/src/components/common/FilterableNamedEntityList.tsx
packages/zapp/console/src/components/flytegraph/ReactFlow/ReactFlowWrapper.tsx

Fixed the search bar functionality for Workflows, Tasks and Launch Plans
https://share.getcloudapp.com/2NumgZkE
https://github.com/flyteorg/flyteconsole/issues/563

fix: fix searchbar X button

---

packages/zapp/console/src/assets/index.html

Webmanifest requests result in error
Added a crossorigin attribute
https://github.com/flyteorg/flyteconsole/issues/565

fix: webmanifest missing crossorigin attribute

---

packages/zapp/console/src/components/Executions/ExecutionDetails/Timeline/ChartHeader.tsx
packages/zapp/console/src/components/Executions/ExecutionDetails/Timeline/ExecutionTimeline.tsx
packages/zapp/console/src/components/Executions/ExecutionDetails/Timeline/TaskNames.tsx
packages/zapp/console/src/components/Executions/Tables/nodeExecutionColumns.tsx
packages/zapp/console/src/components/WorkflowGraph/utils.ts

Some subworkflows compared non-empty objects with `null`, which resulted in the failure to extract fields on a `null` and the whole stack of unresolved computational steps - adding an early exit out of the comparison function, if one of the parameters is null/undefined, resolves the issue with improper populated data in the node executions table.
Before: 
After:
fixes https://github.com/flyteorg/flyteconsole/issues/406
_NA_

fix: console showing subworkflows as unknown

---

packages/zapp/console/src/components/Launch/LaunchForm/MapInput.tsx

Update state with new input
fixes https://github.com/flyteorg/flyte/issues/560

fix: Dict value loses 1 trailing character on UI Launch.

---

packages/zapp/console/src/components/Launch/LaunchForm/LaunchFormInputs.tsx
packages/zapp/console/src/components/Launch/LaunchForm/NoneInput.tsx
packages/zapp/console/src/components/Launch/LaunchForm/UnionInput.tsx
packages/zapp/console/src/components/Launch/LaunchForm/constants.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/none.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/test/testCases.ts
packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/utils.ts
packages/zapp/console/src/components/Launch/LaunchForm/types.ts
packages/zapp/console/src/components/Launch/LaunchForm/utils.ts

Signed-off-by: eugenejahn <eugenejahnjahn@gmail.com>
since we don't support none type, there is an bug in Union Type when using optional type. The reason is optional type will use none type. Since we added the none type support in flyteconsole, there shouldn't have any bugs on union type. 
Issue: https://github.com/flyteorg/flyteconsole/issues/571

added none type in union type

---

packages/zapp/console/src/components/Entities/EntityInputs.tsx

Signed-off-by: Rahul Mehta <rahul@theoremlp.com>
Correctly coerce `defaultValue` to string for default & fixed inputs when rendering LaunchPlan details.
This PR fixes a bug when rendering LaunchPlans with complex objects as fixed or default values. 
* Add  `coerceDefaultValue`, which stringifies any default values that are of type `object`
* Correctly coerce `defaultValue` when rendering fixed & default input tables
Fixes https://github.com/flyteorg/flyte/issues/2845
Fixes #567
N/A

fix: correctly coerce `defaultValue` when rendering LaunchPlan details

---

packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts

Fix inputHelpers test error
We are getting a `Property 'setIsError' is missing in type` error when running coverage

 #minor: inputHelpers InputProps

---

packages/zapp/console/src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts
packages/zapp/console/src/components/Launch/LaunchForm/test/LaunchTaskForm.test.tsx
packages/zapp/console/src/components/Launch/LaunchForm/test/LaunchWorkflowForm.test.tsx

Fixed regression in unit tests.
_NA_

fix: fix test of launchform

---

README.md

feat: minor change

---

packages/zapp/console/src/common/formatters.test.ts
packages/zapp/console/src/common/formatters.ts

Round down number of seconds to int in the edge case moment.js returns it as float.
fixes https://github.com/flyteorg/flyteconsole/issues/568
_NA_

fix: floor seconds to int in the edge case moment returns it as float

---

packages/zapp/console/package.json
packages/zapp/console/webpack.dev.config.ts

Opens the correct window in development and allows directly navigating to deeply nested routes
Added BASE_URL to startup and correct assets path for static content
fixes https://github.com/flyteorg/flyteconsole/issues/588

fix: add BASE_URL to dev startup, open deeply nested urls

---

packages/zapp/console/src/components/Executions/filters/useOnlyMyExecutionsFilterState.ts
packages/zapp/console/src/components/Executions/test/useOnlyMyExecutionsFilterState.test.ts

Added a check to set up default disabled state of the only mine filter based on the auth status - for logged in users it defaults to `enabled`, otherwise `disabled`.
_NA_

fix: add default disabled state for only mine filter

---

packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
packages/zapp/console/src/components/Executions/nodeExecutionQueries.ts
packages/zapp/console/src/components/WorkflowGraph/transformerWorkflowToDag.tsx
packages/zapp/console/src/components/WorkflowGraph/utils.ts

This PR fixes issues related to workflows with reference launch plans. Users reported that nodes in the graph view were not rendering these nodes correctly. The new UX will be for nodes with `launchplanRef` properties to render as standard/task nodes and the launch plan's workflow can be accessed via clicking on the node in the execution detail panel (ie, slide-out panel, "View sub-workflow") 
This fix was verified against `flytesnacks/development/core.control_flow.subworkflows.root_level_wf` and `flytesnacks/development/core.control_flow.subworkflows.other_root_level_wf`
The issue was related to Graph and Timeline views using a map of node executions - since launch plans have independent node id values (ie, nodes aren't scoped) it was causing map collisions and values were be …

Launch plan ref v2

---

packages/zapp/console/package.json
packages/zapp/console/webpack.dev.config.ts

This will allow webpack to properly render deeplinks without defaulting to 404
The reason why deeplinks were not rendering was due to this error:
`Not rewriting GET /console/projects/flytesnacks/domains/development/workflows/core.control_flow.subworkflows.root_level_wf?duration=all because the path includes a dot (.) character.`
This PR disabled the webpack dot rule that was causing certain deeplinks to 404

fix: enable deeplinks in development

---

packages/zapp/console/src/components/Entities/generators.ts
packages/zapp/console/src/components/Executions/Tables/WorkflowVersionRow.tsx

This fixes and incorrect request config that did not account for entity version when it was passed (breaking version-specific views). 
fixes [3136](https://github.com/flyteorg/flyte/issues/3136)
_NA_

Fix: Version executions not being loaded correctly

---

packages/zapp/console/src/components/Navigation/DefaultAppBarContent.tsx

This PR fixes and issue reported by users that the value displayed in the AppInfo component would always return true for "Google Analytics" even when it was actually disabled/not-loaded.
fixes [https://github.com/flyteorg/flyte/issues/613](https://github.com/flyteorg/flyteconsole/issues/613)
_NA_

Fixes the AppInfo window value for GA

---

packages/zapp/console/env.js
packages/zapp/console/src/components/Navigation/DefaultAppBarContent.tsx
packages/zapp/console/src/components/Navigation/strings.ts

This PR fixes the activation of Google Analytics using string 'false' instead of boolean false as the default value of `ENABLE_GA` to align with others
Note that this PR renames `gaDisable` to `gaActive` for consistency.
Based on the root cause described in https://github.com/flyteorg/flyteconsole/issues/614, there is a discrepancy in data type between the environment variable, the local variable, and where it is used. This PR fixes the data type at the local variable definition to align with the other two.
fixes https://github.com/flyteorg/flyteconsole/issues/614
NA

Fix the activation of Google Analytics

---

packages/console/src/components/Executions/ExecutionDetails/Timeline/ExecutionTimeline.tsx
packages/console/src/components/Executions/ExecutionDetails/Timeline/TaskNames.tsx
packages/console/src/components/Executions/Tables/NodeExecutionRow.tsx
packages/console/src/components/Executions/Tables/NodeExecutionsTable.tsx
packages/console/src/components/Executions/Tables/RowExpander.tsx
packages/console/src/components/flytegraph/ReactFlow/ReactFlowWrapper.tsx

chore: fix expander bug

---

packages/console/package.json
packages/console/src/components/Launch/LaunchForm/StructInput.tsx
yarn.lock

Fixes launch form bug for fast-registered workflows
Changed the import for the launch workflow import

chore: launch form bug for fast-registered workflows

---

packages/console/src/components/common/utils.ts

https://github.com/unionai/cloud/issues/1645
_NA_
OR

Perf Refactor: Some parent nodes don't load children

---

packages/console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions.tsx
packages/console/src/components/Executions/Tables/NodeExecutionActions.tsx
packages/console/src/components/Launch/LaunchForm/LaunchFormActions.tsx
packages/console/src/components/Launch/LaunchForm/LaunchFormDialog.tsx
packages/console/src/components/Launch/LaunchForm/ResumeForm.tsx
packages/console/src/components/Launch/LaunchForm/ResumeSignalForm.tsx
packages/console/src/components/Launch/LaunchForm/launchMachine.ts
packages/console/src/components/Launch/LaunchForm/test/ResumeSignalForm.test.tsx
packages/console/src/components/Launch/LaunchForm/useResumeFormState.ts
packages/console/src/components/flytegraph/ReactFlow/PausedTasksComponent.tsx
packages/console/src/components/flytegraph/ReactFlow/customNodeComponents.tsx
packages/console/src/components/flytegraph/ReactFlow/test/PausedTasksComponent.test.tsx

https://github.com/unionai/cloud/issues/1518
The example workflow to reproduce the issue
https://localhost.development.uniondemo.run:3000/projects/flytesnacks/domains/development/workflows/core.control_flow.human_in_the_loop.mainwf?duration=all
To reproduce, you can launch a new workflow and there will be a paused node. You can click the play button and then see the modal for approvedCondition
_NA_
OR

Add support for ApprovedCondition for GateNodes

---

packages/console/package.json
packages/console/src/components/Launch/LaunchForm/useResumeFormState.ts
packages/console/src/components/flytegraph/ReactFlow/PausedTasksComponent.tsx
packages/console/src/components/flytegraph/ReactFlow/test/PausedTasksComponent.test.tsx

Add version bump for ApproveCondition PR

---

packages/console/package.json
packages/console/src/components/Project/ProjectDashboard.tsx
packages/console/src/components/Project/test/ProjectDashboard.test.tsx
packages/console/src/components/common/DomainSettingsSection.tsx
packages/console/src/components/common/strings.ts
packages/console/src/components/common/test/DomainSettingsSection.test.tsx
packages/console/src/models/Common/constants.ts
packages/console/src/models/Project/api.ts
packages/console/src/models/Project/utils.ts

This PR adds support for showing project attributes and project domain attributes in the Project Dashboard for flyteconsole.
Currently, there is no way for users to directly tell project attributes, project domain attributes. This PR adds support for showing project attributes and project domain attributes in the Project Dashboard for flyteconsole.
Note: We currently merge the project attributes with the project domain attributes in a single view. In future and as per designs, we will indicate separately global and project level domain settings so that users can see what changed
[https://github.com/flyteorg/flyteconsole/issues/382](https://github.com/flyteorg/flyteconsole/issues/382)
_https://github.com/flyteorg/flyteconsole/issues/382_

feat: add domain settings for project dashboard

---

packages/console/src/components/Project/test/ProjectDashboard.test.tsx

- fix: project settings dashboard tests failing on domain settings component
NA
_NA_

fix: project settings dashbboard tests

---

Dockerfile
package.json
packages/common/package.json
packages/components/package.json
packages/console/package.json
packages/flyte-api/package.json
packages/flyteidl-types/package.json
packages/locale/package.json
packages/ui-atoms/package.json
website/package.json
yarn.lock

Only generates package types for deployment
Docker build uses build:types instead of build:pack

fix: deployment optimization

---

.github/workflows/checks.yml

upgrade release node version to 18
upgrade release node version to 18

fix: upgrade release node version

---

CONTRIBUTING.md
Makefile
README.md

Fixes update_npmversion Makefile command
Fixes update_npmversion Makefile command

chore: fix update_npmversion

---

Dockerfile
package.json
website/package.json
website/src/server/index.ts
website/webpack.config.ts
website/webpack.utilities.ts
yarn.lock

Simplified Dockerfile, removed webpack-stats-plugin, passes runtime variables to app
* cleaned up Dockerfile
* removed webpack-stats-plugin
* added dotenv.config in server to env vars can be used at runtime

fix: cleanup, passthrough runtime variables

---

packages/console/package.json
packages/console/src/components/Tables/PaginatedDataList.tsx
packages/console/src/routes/routes.ts
website/package.json
yarn.lock

Fixes left nav logic that doesn't accurately update when navigating to a specific workflow version
Updated the workflow detail path to include the workflow version path
To repro:
* checkout branch, run & navigate to [this link
](https://localhost.development.uniondemo.run:3000/console/projects/flytesnacks/domains/development/workflow/1.wf/version/DW6W2hJD0NJeK_EOj5SmPw==) Result: The workflows left nav item should be highlighted
* compare to the same [link in production](https://development.uniondemo.run/console/projects/flytesnacks/domains/development/workflow/1.wf/version/DW6W2hJD0NJeK_EOj5SmPw==)

fix: left nav doesn't accurately update on  workflow version page

---

packages/console/src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx

https://github.com/flyteorg/flyte/issues/3465
The reproduce steps are described in the issue.
How to fix:
on `ExecutionNodeViews`, it reset the NodeExectuionsById. It should merge with the previous states because it could contain the child nodes' data. If it resets it only with the current top node, then the other nodes' status are undefined.
fixes https://github.com/flyteorg/flyte/issues/3465

The rendering of node status in a dynamic workflow is not functioning correctly

---

packages/console/package.json
packages/console/src/components/Executions/TaskExecutionsList/utils.ts
packages/console/src/components/common/MapTaskExecutionsList/TaskNameList.tsx

fix: backfill index on execution task logs

---

.github/workflows/checks.yml

Install dependencies using yarn directly
As suggested by https://github.com/bahmutov/npm-install/issues/146#issuecomment-1169226551, we can leverage `actions/setup-node@v3` to cache dependencies.
N/A
_NA_

Install deps directly in checks.yml

---

packages/console/package.json
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/NodeExecutionInputs.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/NodeExecutionOutputs.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/index.tsx
packages/console/src/components/Executions/TaskExecutionsList/utils.ts
packages/console/src/components/Literals/LiteralMapViewer.tsx
packages/console/src/components/Literals/helpers.ts
packages/console/src/components/common/MapTaskExecutionsList/TaskNameList.tsx
website/package.json
yarn.lock

Map task i/o tabs in details panel don't show correct info when a task is selected 
Map task i/o tabs in details panel don't show correct info when a task is selected

fix: show correct i/o in details panel 

---

packages/console/src/components/Entities/EntityDetails.tsx
packages/console/src/components/Entities/EntitySchedules.tsx
packages/console/src/components/Entities/strings.ts
packages/console/src/components/Entities/test/EntitySchedules.test.tsx
packages/console/src/components/LaunchPlan/LaunchPlanLink.tsx

Add information of launch plan name and version to the workflow's schedule. 
When there are multiple scheduled launchplan bound to a workflow, it is hard to understand which schedule correspond to which launchplan. This PR add additional information in the workflow's schedule to include the launch plan name and version. Additionally, when users clicked the launch plan name it will open the launchplan details page. 
https://user-images.githubusercontent.com/4023015/229272631-5c388db0-35ef-48da-9094-73f42e9ca4dd.mov
fixes [https://github.com/flyteorg/flyte/issues/3554](https://github.com/flyteorg/flyte/issues/3554)
_NA_

feat: show launch plan information in workflow's schedules

---

packages/console/package.json
packages/console/src/components/Executions/TaskExecutionsList/TaskExecutionLogsCard.tsx
packages/console/src/models/Task/index.ts
packages/console/src/models/index.ts

ContextPanel Allow external hooks to have a fallback header
Added a fallback option

chore: add fallback to task execution link 

---

packages/console/package.json
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/index.tsx
packages/console/src/components/common/PanelSection/index.tsx
website/package.json
yarn.lock

Fixes details panel card padding
Added padding to the panel content
_NA_

chore: fix details panel card padding

---

packages/console/package.json
packages/console/src/components/hooks/utils.ts
website/package.json
yarn.lock

Fixes null ref error
Added fallback for when nodes is undefined
_NA_

chore: fix crash

---

packages/console/package.json
packages/console/src/components/Entities/EntitySchedules.tsx
packages/console/src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
packages/console/src/components/Executions/ExecutionDetails/Timeline/NodeExecutionName.tsx
packages/console/src/components/Executions/ExecutionDetails/utils.ts
packages/console/src/components/Executions/TaskExecutionsList/TaskExecutionsList.tsx
packages/console/src/components/Executions/TaskExecutionsList/test/TaskExecutionsList.test.tsx
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/NodeExecutionDetailsContextProvider.tsx
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/utils.ts
packages/console/src/components/Executions/nodeExecutionQueries.ts
packages/console/src/components/Executions/types.ts
packages/console/src/components/Executions/utils.ts
packages/console/src/components/Launch/LaunchForm/utils.ts
packages/console/src/components/Tables/PaginatedDataList.tsx
packages/console/src/components/flytegraph/ReactFlow/customNodeComponents.tsx
packages/console/src/components/hooks/useNodeExecution.ts
packages/console/src/models/Common/types.ts
packages/console/src/models/Execution/__mocks__/mockNodeExecutionsData.ts
packages/console/src/models/Execution/types.ts
website/package.json
yarn.lock

Attaches a dynamicParentNodeId property to all nodes derived from a dynamic execution
Attaches a dynamicParentNodeId property to all nodes derived from a dynamic execution
_NA_
_NA_

chore: propagate dynamic parent id 

---

packages/console/package.json
packages/console/src/components/Entities/EntityDescription.tsx
packages/console/src/components/Task/SimpleTaskInterface.tsx
packages/console/src/components/Workflow/useWorkflowInfoItem.ts
packages/console/src/components/WorkflowGraph/__stories__/WorkflowGraph.stories.tsx
packages/console/src/components/common/DetailsPanel.tsx
packages/console/src/components/data/apiContext.ts
packages/console/src/components/hooks/useDescription.ts
packages/console/src/models/DescriptionEntity/api.ts
packages/console/src/models/DescriptionEntity/types.ts
website/package.json
yarn.lock

Prevents the content panel from capturing focus away from other modals
added disableEnforceFocus to DetailsPanel
_NA_

fix: content panel captures focus 

---

packages/console/package.json
packages/console/src/components/Executions/TaskExecutionsList/MapTaskExecutionListItem.tsx
packages/console/src/components/Executions/TaskExecutionsList/TaskExecutionLogsCard.tsx
packages/console/src/components/common/MapTaskExecutionsList/TaskNameList.tsx
packages/console/src/models/Execution/types.ts
website/package.json
yarn.lock

This PR adds support for a mapped task's parentRetry group provided to the attempts UI.
Adds more correct context to the attempt UI when working with mapped tasks as the current component assumes only the retryAttempt of the mapped execution, not its parent execution. 
_NA_
_NA_

feat: added support for mapped task parent retryAttempt

---

packages/console/package.json
packages/console/src/components/Entities/generators.ts
website/package.json
yarn.lock

filters tasks by version
filters tasks by version
test on:
[wf1](https://development.uniondemo.run/console/projects/flytesnacks/domains/development/workflows/async_prototype.flytekit_async.wf?duration=all)
[wf2](https://development.uniondemo.run/console/projects/flytesnacks/domains/development/workflows/core.containerization.use_secrets.my_secret_workflow?duration=all)
[task 1](https://development.uniondemo.run/console/projects/flytesnacks/domains/development/tasks/async_prototype.flytekit_async.main?duration=all)
[task 2](https://development.uniondemo.run/console/projects/flytesnacks/domains/development/tasks/async_prototype.flytekit_async.get_data?duration=all)
[task 3](https://development.uniondemo.run/console/projects/flytesnacks/domains/development/tasks/async_prototype.flytekit_async …

fix: task recent runs should filter by version

---

packages/console/src/components/Executions/Tables/WorkflowExecutionLink.tsx
packages/console/src/components/Executions/Tables/test/WorkflowExecutionLink.test.tsx

Fixes routing behaviour for back arrow button for Launch Plans workflow execution detail referred pages.
Added `fromLink` to router `state` to use existing logic to match other workflow tables.
_NA_

Bug: Execution Page's back button returns Workflows route from Launch Plan route #patch

---

packages/console/src/components/Entities/EntityDetailsHeader.tsx
packages/console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions.tsx
packages/console/src/components/Executions/ExecutionDetails/ExecutionDetailsAppBarContent.tsx
packages/console/src/components/Executions/ExecutionInputsOutputsModal.tsx
packages/console/src/components/Launch/LaunchForm/LaunchFormDialog.tsx
packages/console/src/components/common/ClosableDialogTitle.tsx
packages/console/src/components/hooks/test/useKeyListener.test.tsx
packages/console/src/components/hooks/useKeyListener.ts

Added a button to allow Flyte Deck modal expands full screen. Also, added escape to close listener for the modal.
Added a button to toggle fullscreen. Passed a conditional CSS class to the `MUI Paper` component to change the size. The full view size accounts for the small view port constraint for tablets and touch screens with dynamic viewport sizing.
Close on `Esc` key is achieved with a `useEffect` document listener pattern.
fixes https://github.com/flyteorg/flyte/issues/2774
https://github.com/flyteorg/flyte/issues/3701
_NA_

Feature: Fullview Flyte Deck modal

---

packages/console/src/components/Launch/LaunchForm/inputHelpers/test/union.test.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/union.ts

Fixed parsing for a more verbose variant of the union data type in the relaunch modal's parsers. This data structure is present on the first relaunch.
Added a check to see if the input value is nested and pass the child nested value to the parser.
fixes https://github.com/flyteorg/flyte/issues/3690
_NA_

Bug: union val missing for LP relaunch

---

packages/console/package.json
packages/console/src/components/Executions/TaskExecutionsList/MapTaskExecutionListItem.tsx
packages/console/src/components/Executions/TaskExecutionsList/TaskExecutionLogsCard.tsx
website/package.json
yarn.lock

Hide map task runtime info
Before :
After:
Before:
After:
Hide map task runtime info
_NA_

chore: hide map task runtime info

---

packages/console/package.json
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/NodeExecutionDetailsContextProvider.tsx
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/getTaskThroughExecution.ts
packages/console/src/components/WorkflowGraph/transformerWorkflowToDag.tsx
website/package.json
yarn.lock

This PR fixes a bug when viewing children of dynamic task where the various information like the task type/template was not correctly being shown. 
The issue was caused by incorrectly referencing task definitions from the (root) `compiledWorkflowClosure` rather than dynamic execution's `workflowClosure`. The result was that row values like task type as well as information in the execution detail panel (slide-out) were null and showing empty values.
fixes [#3455 ](https://github.com/flyteorg/flyte/issues/3455)
_NA_

fix: dynamic-node-tasks

---

packages/console/package.json
packages/console/src/components/Navigation/NavLinkWithSearch.tsx
packages/console/src/components/Navigation/ProjectNavigation.tsx
yarn.lock

fix: preserve project when navigating across tabs using sidebar
- adds a custom `NavLinkWithSearch` component to preserve values across navigation
fixes https://github.com/flyteorg/flyte/issues/3706
_NA_

fix: preserve domain when navigating using sidebar

---

packages/console/package.json
packages/console/src/components/Navigation/NavLinkWithSearch.tsx

Signed-off-by: Soham <4nalog@protonmail.com>
This PR fixes an issue with a mismatched version in `package.json` preventing build.
_NA_
OR

fix: navlink

---

packages/components/package.json
packages/console/package.json
packages/console/src/components/LaunchPlan/SearchableLaunchPlanNameList.tsx
packages/console/src/components/Navigation/ProjectNavigation.tsx
packages/ui-atoms/package.json
packages/ui-atoms/src/Icons/MuiLaunchPlanIcon/index.tsx
website/package.json
yarn.lock

Fixes Launch plan icon to:
* respect selected color
* remove additional margins in side nav
Before:
After:
Fixes Launch plan icon to:
* respect selected color
* remove additional margins in side nav

fix: launch plan icon

---

packages/console/src/components/Navigation/ProjectNavigation.tsx
packages/console/src/components/Navigation/ProjectSelector.tsx
packages/console/src/components/Navigation/SearchableProjectList.tsx
packages/console/src/components/Project/ProjectDashboard.tsx
packages/console/src/components/SelectProject/ProjectList.tsx
packages/console/src/components/common/LocalStoreDefaults.ts
packages/console/src/routes/ApplicationRouter.tsx
packages/console/src/routes/routes.ts

This PR will provide a way to store certain default behaviors/values in `localStorage`. Specifically, this allows users to save a users last selected `project` and `domain` from the project select UI so that subsequent visits will default to those values and skip the need to select project/domain.
- Saves users last selected project/domain in localStorage; will skip the project select UI if value exists in localStorage
- Adds a new "View all projects" link in the project-select dropdown (in left-nav)
- Changes project select URL to `/select-project`
- User intents captured: 
1. User selects from project select view
2. User select from project select drop-down (in side-nav) 
_NA_

Add localStorage for selected Project/Domain

---

package.json
packages/console/src/components/Executions/ExecutionDetails/Timeline/TimelineChart/barOptions.ts
packages/console/src/components/Navigation/ProjectSelector.tsx
yarn.lock

A chart.js import was causing the jest tests to fail.
Moved a way from `registerables` helper to importing the full list to the verbose syntax here: https://www.chartjs.org/docs/3.6.2/getting-started/integration.html
From some light reading it seems like `registrablables` may be generally buggy, even in modern releases.

Fix project selector failing test

---

packages/console/package.json
packages/console/src/components/Navigation/NavLinkWithSearch.tsx
packages/console/src/components/Navigation/SearchableProjectList.tsx
packages/console/src/components/Navigation/strings.ts
packages/console/src/components/common/LocalStoreDefaults.ts
packages/console/src/routes/ApplicationRouter.tsx
website/package.json
yarn.lock

When clicking 'View all projects' users get a bad local storage state that leads to 404's next time they land on the homepage
Replaces the View all projects action to bypass the regular select-project path and directly navigate to the select-project page. Back-compat for users with corrupted states was added in the application router
fixes [#3877](https://github.com/flyteorg/flyte/issues/3877)

chore: fix 404 due to bad state

---

packages/console/package.json
packages/console/src/components/Launch/LaunchForm/LaunchFormComponents/UnionInput.tsx
packages/console/src/components/Launch/LaunchForm/inputHelpers/collection.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/datetime.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/float.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/string.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/test/inputHelpers.test.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/union.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/utils.ts
website/package.json
yarn.lock

Fixes launch form union nonetype bug
Updated the union input value parsing
fixes https://github.com/flyteorg/flyte/issues/3872

Fix: Launch Form fixes

---

packages/console/package.json
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/index.tsx
packages/console/src/components/Executions/ExecutionDetails/strings.tsx
packages/console/src/components/Executions/NodeExecutionCacheStatus.tsx
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/WorkflowNodeExecutionsProvider.tsx
packages/console/src/components/Executions/nodeExecutionQueries.ts
packages/console/src/components/common/MapTaskExecutionsList/TaskNameList.tsx
website/package.json
yarn.lock

Map tasks do not correctly report their caching status
Code updated to correctly track caching status on map tasks. UI updates to not allow cache status icons overflow to the right out of view
_NA_
OR

fix: map tasks should report caching status accurately

---

packages/console/package.json
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/WorkflowNodeExecutionsProvider.tsx
packages/console/src/components/Launch/LaunchForm/LaunchFormComponents/StructuredDatasetInput.tsx
packages/console/src/components/Launch/LaunchForm/LaunchFormComponents/getComponentForInput.tsx
packages/console/src/components/Launch/LaunchForm/UnsupportedRequiredInputsError.tsx
packages/console/src/components/Launch/LaunchForm/constants.ts
packages/console/src/components/Launch/LaunchForm/getInputs.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/blob.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/getHelperForInput.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/structuredDataSet.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/utils.ts
packages/console/src/components/Launch/LaunchForm/strings.ts
packages/console/src/components/Launch/LaunchForm/types.ts
packages/console/src/components/Launch/LaunchForm/useLaunchWorkflowFormState.ts
packages/console/src/components/Launch/LaunchForm/utils.ts
packages/console/src/models/Common/types.ts
website/package.json
yarn.lock

add support from structured datasets
Added support for structured datasets in the launch form
closes https://github.com/flyteorg/flyte/issues/3892 
closes https://github.com/flyteorg/flyte/issues/3395

feat: add support from structured datasets

---

packages/components/package.json
packages/console/package.json
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
packages/console/src/components/Executions/ExecutionDetails/Timeline/TimelineChart/utils.ts
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/WorkflowNodeExecutionsProvider.tsx
packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/utils.ts
packages/console/src/components/WorkflowGraph/transformerWorkflowToDag.tsx
website/package.json
yarn.lock

The task context panel doesn't correctly update its execution status
transformer worklow to dag is mutating state, which is causing certain parts of the ui to not pickup updates

fix: Tasks status out of sync

---

package.json
packages/console/src/components/Entities/test/EntityDetails.test.tsx

chore: fix test_coverage

---

packages/console/package.json
packages/console/src/basics/FeatureFlags/FeatureFlags.tsx
packages/console/src/components/App/App.tsx
website/package.json

Change the feature flag logic priority order.
Old: default, env, default, params,
New: default, env, params
Now:
`default: false` `env: true` will enable a flag
`default: false` `env: true` `params: false` will disable a flag
Tested by adding the breadcrumb env var to `yarn start` script to verify loading order.
fixes https://github.com/flyteorg/flyte/issues/3896
_NA_

Fix: breadcrumb feature flag priority order

---

.github/workflows/checks.yml
.husky/commit-msg
.husky/pre-commit
.releaserc.js
commitlint.config.js
package.json

Commit linter was running on auto-generated content with long URLs to github artifacts, triggering the lines longer than 100 chars rule.
- Made sure CI env variable was set - same as linter stage - that it was bypassing. 
- Added `[skip ci]` rule to the generated commit message which is recommended by semantic-release if running within a CI so you can avoid duplicate builds from change log diffs.
- Remote pipeline is  incrementally more in common with local dev environment.
_NA_

fix: commit linter running on generated messages

---

packages/console/package.json
packages/console/src/components/Launch/LaunchForm/LaunchFormComponents/CollectionList.tsx
packages/console/src/components/Launch/LaunchForm/LaunchFormComponents/UnionInput.tsx
packages/console/src/components/Launch/LaunchForm/constants.ts
packages/console/src/components/Launch/LaunchForm/inputHelpers/union.ts
packages/console/src/components/Launch/LaunchForm/types.ts
packages/console/src/components/Launch/LaunchForm/utils.ts
packages/console/src/models/Common/types.ts
website/package.json
yarn.lock

Union values in unexpected format cause the launch form to crash
Added smarter type detection around union type values

fix: union value handling in launch form

---

packages/console/package.json
packages/console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions.tsx
packages/console/src/components/Executions/ExecutionDetails/ExecutionNodeDeck.tsx
packages/console/src/components/Launch/LaunchForm/inputHelpers/union.ts
website/package.json
yarn.lock

Fix flyte deck height
Updated iframe height and width

fix: flyte decks height

---

packages/console/package.json
packages/console/src/components/Breadcrumbs/components/BreadcrumbPopover.tsx
website/package.json
yarn.lock

fix: invalid item in dropdown

---

packages/console/package.json
packages/console/src/components/Breadcrumbs/async/fn.ts
packages/console/src/components/Breadcrumbs/async/utils.ts
website/package.json
yarn.lock

When switching projects from the breadcrumbs, if domain is anything other than development, it is not respected
Repro steps:
- go to https://development.uniondemo.run/console/projects/flytesnacks/executions?domain=production&duration=all
- switch to llm-fine-tuning (should load production executions, but the requests are actually for development)
- clicking on any of the executions that are loaded leads to development
Added the breadcrumb's domain value to the project's format callback function
fixes https://github.com/flyteorg/flyte/issues/3947

fix: switching projects doesn't respect domain value

---

packages/console/src/components/Launch/LaunchForm/useResumeFormState.ts

Allows relaunch form to deserialize all input types as opposed to just simple

fix: resume form should support all known types

---

packages/console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/NodeExecutionInputs.tsx
packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/NodeExecutionOutputs.tsx

* shows custom FlyteRemote snippet based on protocol used
* hides io uri/usage data when:
* is  map task
* there is no IO

fix: custom flyteremote usage by protocol

---

packages/console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx

Fixes FlyteRemote Usage snippet indentation
_NA_
OR

fix: usage snippet indentation

---

Makefile

`make pack` target doesn't work because a rogue space at the beginning of the line. Removing that so the target works again.
Running `make pack` doesn't work:
```
$ make pack
make: Nothing to be done for 'pack'.
```
This is due to a space at the start of the line. Removing it so only a tab remains, which is a requirement for `Makefile` format. Once done the target works as expected:
```
$ make pack
yarn run build:pack
➤ YN0000: [@flyteorg/common]: Process started
➤ YN0000: [@flyteorg/common]: No matches found: "**.tsbuildinfo"
➤ YN0000: [@flyteorg/common]: Process exited (exit code 0), completed in 8s 258ms
➤ YN0000: [@flyteorg/flyte-api]: Process started
➤ YN0000: [@flyteorg/flyte-api]: No matches found: "**.tsbuildinfo"
➤ YN0000: [@flyteorg/flyte-api]: Process exited (exit code 0), …
```

fix: tab not spaces

---

website/console/env/index.ts

Fix the `yarn start` error in the issue.
Fix the `yarn start` error in the issue by reading from the environment variable instead of hardcoing for the variable `LOCAL_DEV_HOST`.
Resolves: flyteorg/flyte#5075
_NA_

fix(build): Fix yarn start error

---

packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionNodeDeck.tsx

- Add `allow="clipboard-write"` attribute to the SVG element
In order to implement the copy function on the iframe, the iframe needs to add attributes. 
For the reasons, please refer to: https://github.com/flyteorg/flytekit/pull/2264#pullrequestreview-1935703764
_NA_
https://github.com/flyteorg/flytekit/pull/2264

feat: improve security measures in SVG elements

---

.github/workflows/checks.yml
packages/oss-console/src/components/Executions/contextProvider/NodeExecutionDetails/createExecutionArray.tsx
packages/oss-console/src/components/Executions/types.ts
packages/oss-console/src/components/WorkflowGraph/transformerWorkflowToDag.tsx
packages/oss-console/src/components/WorkflowGraph/utils.ts
packages/oss-console/src/models/Node/types.ts

Visualise metadata of array node metadata. This includes the display of the type of the task as well as Task specification of each instance of f.e. array node map tasks
Before:
After:
None

Show Array Node MetaData

---

website/console/env/index.ts

flyteorg/flyteconsole#853 breaks the production environment. This PR partially revert it by making `LOCAL_DEV_HOST` to read from the environment variable instead of a hard-coded value.
Related PR: https://github.com/flyteorg/flyteconsole/pull/864
N/A
_NA_

fix: Partial revert PR #853

---

packages/oss-console/src/components/Entities/EntityInputs.tsx

Fetches latest Entity Details launch plan 
Switched EntityDetails to `useLatestLaunchPlans` hook 
https://github.com/flyteorg/flyte/issues/5271
_NA_

fix: [BUG] Flyteconsole not showing latest LaunchPlan details

---

packages/oss-console/src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx

This PR makes the k8 messages on the Node Execution Details panel collapsible
_NA_
OR

Make k8 messages collapsible on node execution details panel

---

website/console/env/index.ts
website/console/src/server/index.ts

This allows port to be set via env variable and if not set uses default `8080`.
Created an environment variable and use it in the startup code. I've tested this by building a image locally with the env set with a port `9999` and without.
fixes https://github.com/flyteorg/flyte/issues/5347

Alllow port to be set via env instead hardcoded

---

packages/flyte-api/package.json
packages/oss-console/package.json
packages/oss-console/src/App/ApplicationRouter.tsx
packages/oss-console/src/App/index.tsx
packages/oss-console/src/components/Errors/ErrorHandler.tsx
packages/oss-console/src/components/Errors/GenericError.tsx
packages/oss-console/src/components/common/ErrorBoundary.tsx
packages/oss-console/src/components/data/QueryAuthorizationObserver.tsx
packages/oss-console/src/components/data/axiosClient.tsx
packages/oss-console/src/components/data/globalQueryClient.ts
packages/oss-console/src/components/data/loadChunkWithAuth.tsx
packages/oss-console/src/models/AdminEntity/AdminEntity.ts
packages/oss-console/src/test/setupTests.ts
website/console/package.json
yarn.lock

* Update axios
* Attempt to refresh auth token in the background when encountering 401's
* Better error messaging
_NA_
OR

fix: Refresh auth on 401, better error messaging

---

packages/oss-console/src/components/Executions/Tables/useWorkflowVersionsTableColumns.tsx

fix: Active badge overlaps text in LaunchPlan versions table

---

packages/oss-console/src/components/Entities/constants.ts

This PR hides the schedules UI from the Launch Plan details view.
_NA_
OR

feat: remove schedules ui from LP detail page

---

packages/oss-console/src/components/Breadcrumbs/registry/index.ts

Typo – causes breadcrumbs to not appear in flyteconsole. To fix, use BASE_URL not BASE_PATH.
Missing breadcrumbs for custom BASE_URL like `/custom-base/console`
Expectation: breadcrumbs are present for custom BASE_URL Flyte instance.
This happens because when `BASE_PATH` is used instead of `BASE_URL`, the logic that generates the breadcrumbs at `breadcrumbRegistry.breadcrumbBuilder` ends up using the wrong `BASE_URL` value (this starts from `makeUrlSegments`). This causes it to parse the window location incorrectly, and the resulting generated breadcrumbs is missing the expected entries. 
_NA_
OR

fix: Broken breadcrumbs when using custom BASE_URL

---

packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/constants.ts
packages/oss-console/src/components/Executions/ExecutionDetails/test/ExecutionMetadata.test.tsx
packages/oss-console/src/models/__mocks__/executionsData.ts

This PR displays the Parent execution as a link, allowing users to quickly navigate to it.

feat: Execution Detail Page Link to Parent

---

packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionLabels.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/constants.ts
packages/oss-console/src/components/Executions/ExecutionDetails/test/ExecutionLabels.test.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/test/ExecutionMetadata.test.tsx
packages/oss-console/src/models/__mocks__/executionsData.ts

This PR adds the spec labels to the execution details page

feat: display labels on execution detail page

---

packages/common/src/environment/index.ts
packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx
website/console/env/index.ts

The inputs/outputs Python code snippet leads to a "Failed to connect" error
Introduce the environment variable `CODE_SNIPPET_USE_AUTO_CONFIG`, to control whether the config object in the inputs/outputs Python code snippet is automatically constructed i.e. `Config.auto()`. This will tend to use the `admin.endpoint` that users can set in their `~/.flyte/config.yaml`
It can be left unset to keep [the current behavior e.g. uses `Config.for_endpoint(window.location.host)`
](https://github.com/flyteorg/flyteconsole/blob/7636e32d2b1dbefb7d08fb79e5ed063c3ad44ca4/packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx#L39)
Users already configure flytekit in `~/.flyte/config.yaml` to set `admin.endpoint` to the correct gRPC endpoint. We can leverage this by using …

fix: Add CODE_SNIPPET_USE_AUTO_CONFIG environment variable

---

package.json
packages/oss-console/src/components/Launch/LaunchForm/LaunchFormComponents/StructInput.tsx
packages/oss-console/src/components/Launch/LaunchForm/inputHelpers/struct.ts
packages/oss-console/src/components/Literals/helpers.ts
packages/oss-console/src/components/Literals/test/helpers/genScalarBinaryTestCase.mock.ts
packages/oss-console/src/test/setupTests.ts
script/test/jest-setup.ts
yarn.lock

Add msgpack IDL support for the launch form, including input displaying and relaunch input recovering.
Test case: hhttps://localhost.dogfood.cloud-staging.union.ai:8080/console/projects/flytesnacks/domains/development/executions/acj8vfbt8722wg4q46nv

feat: Launch Form Msgpack IDL Supporting

---

package.json
packages/common/package.json
packages/common/src/flyteidl/google.ts
packages/oss-console/package.json
packages/oss-console/src/App/index.tsx
packages/oss-console/src/common/decodeMsgPackLiterals.ts
packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionLabels.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/test/ExecutionLabels.test.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/test/ExecutionMetadata.test.tsx
packages/oss-console/src/components/Launch/LaunchForm/LaunchFormComponents/StructInput.tsx
packages/oss-console/src/components/Launch/LaunchForm/inputHelpers/struct.ts
packages/oss-console/src/components/Literals/helpers.ts
packages/oss-console/src/components/Literals/test/helpers/genScalarBinaryTestCase.mock.ts
packages/oss-console/src/models/__mocks__/executionsData.ts
packages/oss-console/src/test/setupTests.ts
script/test/jest-setup.ts
yarn.lock

Decodes msgpack structs and turns them into flyte literals
* `ADMIN_API_URL=https://dogfood.cloud-staging.union.ai BASE_HREF=https://dogfood.cloud-staging.union.ai yarn start`
* go to https://localhost.dogfood.cloud-staging.union.ai:8080/console/projects/flytesnacks/domains/development/executions/axfdc2b8m8mchw72v2wp/nodes
Decodes msgpack structs and turns them into flyte literals
_NA_
OR

feat: Pre-emptively decode binary literals

---

packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions/FlyteDeckButton.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionNodeDeck.tsx

Show flyte deck when running phase and terminal phase (include failed) 
This pull request (PR) introduces several enhancements and fixes to the FlyteDeckButton and ExecutionNodeDeck components in the Flyte console. Here's a summary of the changes:
1. **FlyteDeckButton Component:**
- Added a `RefreshIcon` button to allow users to refresh the deck content.
- Integrated a `useDownloadLink` hook to manage the download link for the deck.
- Removed the `disabled` state from the button that opens the deck, allowing it to be clicked regardless of the node execution phase.
- Updated the `ExecutionNodeDeck` component to accept a `downloadLink` prop.
2. **ExecutionNodeDeck Component:**
- Added error handling for `NotFoundError` to display a user-friendly message when the deck is not yet available.
- …

feat: Streaming Decks

---

packages/oss-console/src/components/Entities/generators.ts
packages/oss-console/src/components/Workflow/SearchableWorkflowNameList.tsx

This addresses the issue described in https://github.com/flyteorg/flyte/issues/6428 where DB queries don't use the indexes on the `workflows`, `tasks` and `lanuchplans` table. This slows down the UI significantly and spikes the CPU usage of the database server.
The index in the database is over the three columns `(name, project, domain)` - not JUST `name`. Therefore when filtering, we need to pass all these values in order to leverage the index.
fixes https://github.com/flyteorg/flyte/issues/6428

Add project and domain filters in order to hit DB index #patch

---

packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
packages/oss-console/src/components/Executions/ExecutionDetails/constants.ts

This adds `principal` on the execution details page.   
Often time; we want to show the user who started the wf executions. While the data bering returned from the Flyte Admin API in the response; it's not rendered anywhere in the UI. This PR adds the user on the execution details page
_NA_
_NA_

Feat: [feature][QoL] Adds user to the execution details page

---

packages/oss-console/src/common/decodeMsgPackLiterals.ts

Fixes client error when decoding binding data.
- [x ] Bug Fix
- [x ] Code completed
BindingDataCollection is causing a failure in the client during serialization

fix: failure to decode BindingDataCollection
