- boilerplate/update.cfg
- boilerplate/update.sh
Adds flyte wide standard pull request template for Console
updated using boilerplate
https://github.com/lyft/flyte/issues/194
NA
> Add standard pull request template for Console

- package.json
> Bumping to 0.4.0

- package.json
> Bumping version to 0.5.0

- package.json
> Bumping to 5.0.1

- src/components/Launch/constants.ts
Remove the unused constant that was added mistakenly when working on #107 .
It was a change that shouldn't be committed.
https://github.com/lyft/flyte/issues/529
_NA_
> fix: remove not used constant

- .github/workflows/release.yml
- Dockerfile
Migrate to github container registry.
https://github.com/lyft/flyte/issues/627
> Push to Container Registry

- jest.config.js
- package.json
- src/components/Launch/LaunchForm/LaunchRoleInput.tsx
- src/flyteidl/index.ts
- yarn.lock
Signed-off-by: Haytham Abuelfutuh <haytham@afutuh.com>
Update to latest flyteidl
flyteorg/flyte#800
> Update to latest flyteIdl

- README.rst
Signed-off-by: Ketan Umare <ketan.umare@gmail.com>
With the new getting started flow, it is fast to get a new flyteconsole test environment setup quickly
> Update readme to help get running with a local dev environment of flyteconsole

- .github/workflows/release-automation.yml
- Replace package manager from npm to yarn in CI
https://github.com/lyft/flyte/issues/868
_NA_
OR
_https://github.com/lyft/flyte/issues/<number>_
> Replace package manager from npm to yarn in CI

- package.json
- src/components/Executions/ExecutionDetails/TaskExecutionNodeRenderer/TaskExecutionNode.tsx
- src/components/Executions/constants.ts
- yarn.lock
Add rendering for new DYNAMIC_RUNNING node exex. phase
https://github.com/flyteorg/flyte/issues/928
_NA_
> Add rendering for new DYNAMIC_RUNNING node exex. phase

- package.json
- src/components/Launch/LaunchForm/StructInput.tsx
- src/components/Launch/LaunchForm/inputHelpers/struct.ts
- yarn.lock
This PR gives ability to enter valid json instead of arbitrary json when working with Generic Structs data in launch forms.
fixes https://github.com/flyteorg/flyte/issues/1216
> feat: schema validator for struct type execution

- src/common/constants.ts
- src/components/Entities/EntityDetails.tsx
- src/components/Entities/EntityVersions.tsx
- src/components/Entities/constants.ts
- src/components/Executions/Tables/WorkflowVersionRow.tsx
- src/components/Executions/Tables/WorkflowVersionsTable.tsx
- src/components/Executions/Tables/constants.ts
- src/components/Executions/Tables/styles.ts
- src/components/Executions/Tables/types.ts
- src/components/Executions/Tables/useWorkflowVersionsTableColumns.tsx
- src/components/hooks/useWorkflowVersions.ts
Signed-off-by: csirius <davidtruong.dev@gmail.com>
Added Workflow versions table to show executions based on workflow version.
implements https://github.com/flyteorg/flyte/issues/1386
_NA_
> feat: add workflow versions table

- src/components/Executions/ExecutionDetails/ExecutionMetadata.tsx
- src/components/Executions/ExecutionDetails/ExecutionNodeViews.tsx
- src/components/Executions/Tables/ExpandableExecutionError.tsx
- src/components/Executions/Tables/NodeExecutionChildren.tsx
- src/components/Executions/Tables/NodeExecutionRow.tsx
- src/components/Executions/Tables/NodeExecutionsTable.tsx
- src/components/Executions/Tables/WorkflowExecutionRow.tsx
Provide better report on root cause of aborted workflows
fixes https://github.com/flyteorg/flyte/issues/408
> improvement: show proper error message for aborted workflows

- src/components/Launch/LaunchForm/inputHelpers/string.ts
This adds validation on the input to ensure no leading/trailing whitespace.
fixes https://github.com/flyteorg/flyte/issues/909
_NA_
> fix: ensure no leading or trailing whitespace on the string input

- src/components/Executions/constants.ts
- src/components/Executions/types.ts
- src/components/Theme/constants.ts
- src/models/Task/constants.ts
Until we read task type from the task template itself, this PR adds handling for MPI task types
https://github.com/flyteorg/flyte/issues/1393
_NA_
> (feat) Introduce MPI task type

- src/components/Entities/EntityDetails.tsx
Add `min-height` for the `All executions in the workflow` view.
Add `min-height` to the entity executions view and make it scrollable.
fixes https://github.com/flyteorg/flyte/issues/1517
_NA_
> feat: add min height for all executions list

- src/components/Entities/EntityExecutionsBarChart.tsx
- src/components/common/BarChart.tsx
Add popover to bar chart item
Added Popover to bar chart item with execution id, runtime duration and started at time.
fixes https://github.com/flyteorg/flyte/issues/1465
_NA_
> feat: add popover for bar chart item hover state

- src/components/Entities/EntityExecutionsBarChart.tsx
This code is failing if an execution is still on UNKNOWN phase.
When the execution transitions to QUEUED/RUNNING then it stops crashing
_NA_
OR
> avoid empty startedAt to crash console

- src/components/Navigation/VersionDisplayModal.tsx
This adds clickable links attached to the version number.
> fix: add links to version number

- src/components/Executions/types.ts
- src/components/Executions/useNodeExecutionDetails.ts
This allows users to see the arbitrary task type.
fixes https://github.com/flyteorg/flyte/issues/1393
_NA_
> fix: show correct task type in execution view

- README.rst
Signed-off-by: Ketan Umare <ketan.umare@gmail.com>
Past couple commits have not been released
fixes https://github.com/flyteorg/flyte/issues/1841
_NA_
> #minor PR to bump release version and explain how to

- README.rst
A small change to trigger release since https://github.com/flyteorg/flyteconsole/commit/39efa13c5091b85b3d96f2c4ae383382b54fb489 was incorrectly annotated.
> #minor Small change to trigger release

- src/components/Entities/EntityExecutions.tsx
fixes https://github.com/flyteorg/flyte/issues/2015
_NA_
> feat: load 100 executions on each filter

- README.md
Updated README.md with proper links to CONTRIBUTING.md which are not depend on the branch you are in.
> chore: Update README.md links to inner files

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
This PR ensures that default VsCode recommendations and workflow settings can be populated by all users. 
It will minimize additional eslint updates, after code completition.
> chore: update vscode workspace default settings #patch

- .eslintignore
- .github/workflows/checks.yml
- .tool-versions
- Dockerfile
- package.json
- tsconfig.json
- yarn.lock
This PR updates flyteconsole package to latest nodejs LTS version.
https://github.com/flyteorg/flyteconsole/issues/342
> ci: update nodejs version to latest LTS 16 #patch

- src/components/WorkflowGraph/transformerWorkflowToDag.tsx
Current Graph and timeline were crashing miserably in one corner case scenario:
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/workflows/core.control_flow.subworkflows.parent_workflow?duration=all
Ensure that the data we iterate through is accessible
Fix working video:  https://share.getcloudapp.com/geumRYnA
Additional Task would be created to cover rendereing issue.
> fix: fix the crash in graph/timeline view for corner case

- CONTRIBUTING.md
- README.md
Updating instructions for which Chrome browser extension we use for CORS
Updated Readme
> chore: update readme CORS ext

- package.json
- src/components/flytegraph/ReactFlow/ReactFlowWrapper.tsx
- yarn.lock
Updated `react-flow-renderer` to the most recent stable version `v10.1.1`.
fixes https://github.com/flyteorg/flyte/issues/377
> chore: update react-flow-renderer version

- .github/workflows/checks.yml
Added CI for devmain branch 
_NA_
OR
> ci: added for devmain branch

- package.json
Adding build and start scripts for local dev
_NA_
OR
> chore: add build scripts for console app

- packages/zapp/console/src/components/flytegraph/ReactFlow/NodeStatusLegend.tsx
change the default state to false (btw look like CI for devmain is broken.)
really quick fix. also add the props to change the default value if needed oneday. 
fixes https://github.com/flyteorg/flyteconsole/issues/376
_NA_
OR
> fix issue 376

- packages/zapp/console/src/components/Tables/DataList.tsx
fixed by updating the state and recalculating row size 
when the rows update(adding or removing item), recalculate the size and cache it in the state. 
fixes https://github.com/flyteorg/flyteconsole/issues/386
_NA_
OR
> fix: When users manually selects failed workflow - it is truncated in a weird wa

- .babelrc
- .gitignore
- package.json
- packages/zapp/console/env.js
- packages/zapp/console/index.js
- packages/zapp/console/package.json
- packages/zapp/console/src/common/utils.ts
- packages/zapp/console/src/components/Launch/LaunchForm/BlobInput.tsx
- packages/zapp/console/src/components/common/FilterableNamedEntityList.tsx
- packages/zapp/console/src/components/common/SearchableList.tsx
- packages/zapp/console/src/components/common/SearchableNamedEntityList.tsx
- packages/zapp/console/tsconfig.json
- packages/zapp/console/webpack.dev.config.ts
- script/generate_ssl.sh
- tsconfig.base.json
- Unified tconfig.json, to mnimize config size for all new packaged
- Updated tsconfig to ensure that test , mocks, stories will be excluded from the build
- Added basic `clean` function as it is needed for make_build production (this step will still be red in CI)
- Removed empty files
- Removed some unused variables 
- Updated one of the export to semanticly proper TS usage
Also Moved certificates into script/certificate folder to allow more scripts to live there. I would need that folder for jest setup.
To minimize user interruptions added an early exit to webpack with certificate regeneration info:
Work is related to: https://github.com/flyteorg/flyteconsole/issues/431
> ci: ensure unified tsconfig and remove mocks, test, stories from build

- packages/zapp/console/src/components/flytegraph/ReactFlow/transformDAGToReactFlowV2.tsx
[Graph][BUG] Unable to view all the workflow versions
Added null checks to allow data types to populate
fixes  https://github.com/flyteorg/flyteconsole/issues/416
> minor: unable to view all the workflow versions

- packages/zapp/console/package.json
Only package version change, 
Needed to publish new release: https://github.com/flyteorg/flyteconsole/issues/500
> chore: update release version

- package.json
- packages/zapp/console/package.json
Updated package version, for release 1.1.3
Signed-off-by: Work <awork@narusina.fritz.box>
> chore: release 1.1.3

- packages/zapp/console/src/components/Launch/LaunchForm/MapInput.tsx
- packages/zapp/console/src/components/Launch/LaunchForm/__stories__/MapInput.stories.tsx
Sample for James.
@james-union You can play around with validation in storybook.
To run storybook use `yarn storybook` from top level
MapInput located under Launch section (see screnshot)
If you open DevTools->Console you will see what is send on `onChange` event to parent control
> chore: storybook item

- .releaserc.json
fix semantic-release config
_NA_
OR
> fix: fix semantic-release config

- packages/zapp/console/package.json
- packages/zapp/console/src/components/flytegraph/ReactFlow/ReactFlowWrapper.tsx
- yarn.lock
Make the graph to be center on initial render
It's all about `fitView` for the flowInstance. But while the flowInstance does `fitView`, it shouldn't be re-rendered which stops that `fitView` stuff of flowInstance internally. (Just guessing).
So I merge the state (which was separated by rf & state) and does `fitView` on nodesChange. (several useEffect may raise race conditions)
fixes https://github.com/flyteorg/flyte/issues/524
> fix: Graph Center on initial render

- .github/workflows/checks.yml
Bug fix, Enable docker push for console image
_NA_
OR
> enable docker push for console

- packages/zapp/console/package.json
- yarn.lock
This PR prunes unused packages
_NA_
> Pruning some unused packages

- package.json
> chore: release 1.3.5

- packages/zapp/console/src/components/Launch/LaunchForm/LaunchFormActions.tsx
- packages/zapp/console/src/components/Launch/LaunchForm/test/ResumeSignalForm.test.tsx
- packages/zapp/console/src/components/Launch/LaunchForm/test/constants.ts
- packages/zapp/console/src/components/Launch/LaunchForm/useResumeFormState.ts
Added a test for ResumeSignalForm.
Also, slightly fixed some issues for generating the compiledNode.
> Signal Form Test

- .eslintignore
- package.json
- packages/zapp/console/package.json
- packages/zapp/console/src/components/Executions/CacheStatus.tsx
- packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionDetailsActions.tsx
- packages/zapp/console/src/components/Executions/ExecutionDetails/ExecutionNodeDeck.tsx
- packages/zapp/console/src/components/Executions/constants.ts
- packages/zapp/console/src/components/Executions/strings.ts
- packages/zapp/console/src/components/hooks/useDataProxy.ts
- packages/zapp/console/src/models/Common/constants.ts
- packages/zapp/console/src/models/Execution/api.ts
- packages/zapp/console/src/models/Execution/types.ts
- packages/zapp/console/src/models/Execution/utils.ts
- yarn.lock
Deprecate CreateDownloadLocation API to allow for a more controllable CreateDownloadLink API
Replaced artifact_urn request with artifact_link
https://github.com/flyteorg/flyte/issues/3034
> chore: update flytedecks download link

- packages/zapp/console/env.js
- packages/zapp/console/src/client.tsx
Replaces a Google Analytics key with an empty value.
fixes https://github.com/flyteorg/flyteconsole/issues/641
_NA_
> Remove Google Analytics Key

- packages/common/src/environment/index.ts
- packages/console/src/components/Navigation/utils.ts
- packages/console/src/config/types.ts
- packages/console/src/models/AdminEntity/AdminEntity.ts
https://github.com/flyteorg/flyteconsole/issues/646
> Add support for header options & Revert Env for FlyteNavigationData

- .github/workflows/checks.yml
- Dockerfile
Depends on: https://github.com/flyteorg/flytetools/pull/70
> Publish multi-architecture image

- packages/flyteidl-types/package.json
- yarn.lock
Update @flyteorg/flyteidl to version 1.3.4
Update @flyteorg/flyteidl to version 1.3.4
> chore: update flyteidl version @1.3.4

- package.json
Small fix to revert package.json version back to 1.4 to prep for monorepo. 
_NA_
OR
> fix: package version to 1.4.2

- .github/workflows/checks.yml
> fix: upgrading node version to 18

- .github/workflows/checks.yml
- .tool-versions
- Dockerfile
Reverts codebase node version
Reverts codebase node version
> fix: revert node version

- Makefile
- website/package.json
Fixes bug in update_npmversion script
Fixes bug in update_npmversion script
> fix: update_npmversion

- Makefile
Fixes sed error
Fixes sed error
> fix: fix sed makefile error

- .github/workflows/checks.yml
- .tool-versions
https://github.com/flyteorg/flyte/issues/3415
With node v16, semantic-release did not work
https://github.com/flyteorg/flyte/issues/3415
> FE: Update flyteconsole to Node 18

- Makefile
- package.json
- packages/console/package.json
- packages/console/src/components/Executions/Tables/EntityVersionsTable.tsx
- packages/console/src/models/Common/utils.ts
- packages/console/src/routes/routes.ts
- website/package.json
- yarn.lock
The client drops wf versions that have slashes
Added encoding of wf versions
> chore: allow complex workflow names

- packages/console/src/components/Executions/CacheStatus.tsx
https://github.com/flyteorg/flyte/issues/3430#event-8710740991
I've added this icon (pointing with red)
fixes https://github.com/flyteorg/flyte/issues/3430
> feat: differentiate between cache disabled and cache put failure

- packages/components/src/AppInfo/index.tsx
- packages/console/src/components/App/App.tsx
Adds material-ui classname seed to avoid classname collision
Adds material-ui classname seed to avoid classname collision
> fix: add material-ui class name seed

- .github/workflows/checks.yml
- .github/workflows/upgrade_automation.yml
- website/package.json
- yarn.lock
Upgrading actions to fix hooks error
Upgrated to:
* actions/checkout@v3
* actions/setup-node@v3
*
> fix: release fail

- packages/console/package.json
- packages/console/src/components/common/index.ts
- website/package.json
- yarn.lock
Export ScrollableMonospaceText
https://github.com/unionai/cloud/issues/2759
> TLM add log-message window to left panel

- CONTRIBUTING.md
- README.md
Removes legacy references to DISABLE_AUTH from readme s
Removes legacy references to DISABLE_AUTH from readme s
_NA_
> chore: remove disable_auth from docs

- package.json
- packages/console/package.json
- website/package.json
- yarn.lock
Fixes improperly added dependency
Traverse was added to the workspace package.json instead of the console package
_NA_
> fix: missing dependency

- packages/console/package.json
- packages/console/src/components/Entities/generators.ts
- website/package.json
- yarn.lock
Workflow executions queries should filter by version + name
Workflow executions queries should filter by version + name
_NA_
> fix: filter executions by version and name

- packages/console/package.json
- packages/console/src/components/Executions/TaskExecutionsList/MapTaskExecutionDetails.tsx
- packages/console/src/components/Executions/TaskExecutionsList/TaskExecutionLogsCard.tsx
- packages/console/src/components/Executions/contexts.ts
- packages/console/src/models/Task/index.ts
- website/package.json
- yarn.lock
Note: This PR is WIP
Adds a more correct context to the attempts UI when dealing with mapped tasks. 
_NA_
_NA_
_NA_
> chore: add item when mapped task

- packages/console/package.json
Fix version to bump to fix build for flyte/console
> fix: bump version for console

- packages/console/src/components/Navigation/TopLevelLayout.tsx
- packages/console/src/routes/ApplicationRouter.tsx
Add ability for subnav on all paths
_NA_
OR
> chore: restore subnav

- packages/console/package.json
- packages/console/src/components/Executions/nodeExecutionQueries.ts
- packages/console/src/components/common/utils.ts
- website/package.json
- yarn.lock
Fixes Cannot read property 'scopedId' of undefined
Fixes Cannot read property 'scopedId' of undefined
> chore: dparent null in alt paths

- packages/console/src/components/common/index.ts
> chore: export storage utils

- packages/console/src/routes/ApplicationRouter.tsx
> chore: enhance application router

- packages/console/package.json
- packages/console/src/components/Executions/TaskExecutionsList/test/TaskExecutionDetails.test.tsx
- packages/console/src/components/Executions/contextProvider/NodeExecutionDetails/WorkflowNodeExecutionsProvider.tsx
- packages/console/src/components/WorkflowGraph/transformerWorkflowToDag.tsx
- website/package.json
- yarn.lock
Fixes: node execution list disappearing
Null ref causes the execution list to be wiped out
_NA_
_NA_
> fix: node executions list going blank

- .github/workflows/checks.yml
Enforce node version 18.16.1 for releases
Enforce node version 18.16.1 for releases
> chore: fix release retry

- packages/console/src/components/Breadcrumbs/components/BreadcrumbFormControl.tsx
- packages/console/src/components/Breadcrumbs/components/BreadcrumbPopover.tsx
- packages/console/src/components/Breadcrumbs/registry/utils.ts
- packages/console/src/components/Breadcrumbs/types.ts
Case for hiding dropdown button conflicted with minified build code.
fixes https://github.com/flyteorg/flyte/issues/3974
_NA_
> fix: breadcrumb dropdown render

- packages/console/src/components/Launch/LaunchForm/inputHelpers/collection.ts
- packages/console/src/components/Launch/LaunchForm/inputHelpers/integer.ts
fixes launch form crash on collection of ints
https://github.com/flyteorg/flyte/issues/4033
> fix: optional list arg is causing ui launch form to white screen

- packages/console/src/components/Literals/helpers.ts
Shows correct IO info in details panel
> fix: show correct details panel io

- .github/workflows/upgrade_automation.yml
Fix generation of flyteidl automatic bump in gh workflow
Upgrade `yarn` command
_NA_
OR
> fix: generation of flyteidl bump in gh workflow

- package.json
- packages/console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx
- packages/console/src/components/Executions/ExecutionDetails/NodeExecutionDetailsPanelContent.tsx
- packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/NodeExecutionInputs.tsx
- packages/console/src/components/Executions/ExecutionDetails/NodeExecutionTabs/NodeExecutionOutputs.tsx
- packages/console/src/components/Executions/ExecutionDetails/utils.ts
- packages/console/src/models/Execution/types.ts
- packages/flyteidl-types/package.json
- yarn.lock
* Shows Context Panel IO URLs
* Shows Context Panel IO FlyteRemote usage
* Shows Context Panel node execution logs
|        |           |
| ------------- |:-------------:| 
| <img width="428" alt="image" src="https://github.com/flyteorg/flyteconsole/assets/6610300/b1bc6b63-058e-48ae-a5ff-7f36de18e626">| <img width="438" alt="image" src="https://github.com/flyteorg/flyteconsole/assets/6610300/a08eae53-e1dd-4140-b004-4ec6275e1b05"> |
| <img width="438" alt="image" src="https://github.com/flyteorg/flyteconsole/assets/6610300/5f95508c-7a24-49be-891f-6c00dabcffd3"> | <img width="435" alt="image" src="https://github.com/flyteorg/flyteconsole/assets/6610300/5fd2e552-9310-4444-979b-e4dce163fd6d"> |
_Remove the '*fixes*' …
> feat: show io urls & flyteremote usage

- package.json
- yarn.lock
This PR adds `semantic-release` dependencies
_NA_
OR
> Added semantic release deps back

- Makefile
> feat: Modify placeholder

- packages/common/src/environment/index.ts
- packages/oss-console/src/components/Executions/Tables/styles.tsx
- website/console/env/index.ts
Tiny PR to fix some typos.
fixes https://github.com/flyteorg/flyte/issues/5348
> Fix some typos so IDE highlights the fields

- packages/oss-console/src/components/WorkflowGraph/transformerWorkflowToDag.tsx
Add failure node support for workflow execution details including Nodes, graph, and timeline
_NA_
OR
> feat: add failure node support
